# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import provider_pb2 as provider__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in provider_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShioajiProviderStub(object):
    """ShioajiProvider service provides a gRPC interface for trading and market data access
    using the Shioaji API (Taiwanese stock and futures trading).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/v1.ShioajiProvider/Login',
                request_serializer=provider__pb2.LoginRequest.SerializeToString,
                response_deserializer=provider__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/v1.ShioajiProvider/Logout',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetUsage = channel.unary_unary(
                '/v1.ShioajiProvider/GetUsage',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.UsageStatus.FromString,
                _registered_method=True)
        self.ListAccounts = channel.unary_unary(
                '/v1.ShioajiProvider/ListAccounts',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.ListAccountsResponse.FromString,
                _registered_method=True)
        self.GetAccountBalance = channel.unary_unary(
                '/v1.ShioajiProvider/GetAccountBalance',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.AccountBalance.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/v1.ShioajiProvider/PlaceOrder',
                request_serializer=provider__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=provider__pb2.Trade.FromString,
                _registered_method=True)
        self.PlaceComboOrder = channel.unary_unary(
                '/v1.ShioajiProvider/PlaceComboOrder',
                request_serializer=provider__pb2.PlaceComboOrderRequest.SerializeToString,
                response_deserializer=provider__pb2.ComboTrade.FromString,
                _registered_method=True)
        self.UpdateOrder = channel.unary_unary(
                '/v1.ShioajiProvider/UpdateOrder',
                request_serializer=provider__pb2.UpdateOrderRequest.SerializeToString,
                response_deserializer=provider__pb2.Trade.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/v1.ShioajiProvider/CancelOrder',
                request_serializer=provider__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=provider__pb2.Trade.FromString,
                _registered_method=True)
        self.CancelComboOrder = channel.unary_unary(
                '/v1.ShioajiProvider/CancelComboOrder',
                request_serializer=provider__pb2.CancelComboOrderRequest.SerializeToString,
                response_deserializer=provider__pb2.ComboTrade.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/v1.ShioajiProvider/UpdateStatus',
                request_serializer=provider__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=provider__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateComboStatus = channel.unary_unary(
                '/v1.ShioajiProvider/UpdateComboStatus',
                request_serializer=provider__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=provider__pb2.Empty.FromString,
                _registered_method=True)
        self.ListTrades = channel.unary_unary(
                '/v1.ShioajiProvider/ListTrades',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.ListTradesResponse.FromString,
                _registered_method=True)
        self.ListComboTrades = channel.unary_unary(
                '/v1.ShioajiProvider/ListComboTrades',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.ListComboTradesResponse.FromString,
                _registered_method=True)
        self.GetOrderDealRecords = channel.unary_unary(
                '/v1.ShioajiProvider/GetOrderDealRecords',
                request_serializer=provider__pb2.GetOrderDealRecordsRequest.SerializeToString,
                response_deserializer=provider__pb2.GetOrderDealRecordsResponse.FromString,
                _registered_method=True)
        self.ListPositions = channel.unary_unary(
                '/v1.ShioajiProvider/ListPositions',
                request_serializer=provider__pb2.ListPositionsRequest.SerializeToString,
                response_deserializer=provider__pb2.ListPositionsResponse.FromString,
                _registered_method=True)
        self.ListPositionDetail = channel.unary_unary(
                '/v1.ShioajiProvider/ListPositionDetail',
                request_serializer=provider__pb2.ListPositionDetailRequest.SerializeToString,
                response_deserializer=provider__pb2.ListPositionDetailResponse.FromString,
                _registered_method=True)
        self.ListProfitLoss = channel.unary_unary(
                '/v1.ShioajiProvider/ListProfitLoss',
                request_serializer=provider__pb2.ListProfitLossRequest.SerializeToString,
                response_deserializer=provider__pb2.ListProfitLossResponse.FromString,
                _registered_method=True)
        self.ListProfitLossDetail = channel.unary_unary(
                '/v1.ShioajiProvider/ListProfitLossDetail',
                request_serializer=provider__pb2.ListProfitLossDetailRequest.SerializeToString,
                response_deserializer=provider__pb2.ListProfitLossDetailResponse.FromString,
                _registered_method=True)
        self.ListProfitLossSummary = channel.unary_unary(
                '/v1.ShioajiProvider/ListProfitLossSummary',
                request_serializer=provider__pb2.ListProfitLossSummaryRequest.SerializeToString,
                response_deserializer=provider__pb2.ListProfitLossSummaryResponse.FromString,
                _registered_method=True)
        self.GetSettlements = channel.unary_unary(
                '/v1.ShioajiProvider/GetSettlements',
                request_serializer=provider__pb2.GetSettlementsRequest.SerializeToString,
                response_deserializer=provider__pb2.GetSettlementsResponse.FromString,
                _registered_method=True)
        self.ListSettlements = channel.unary_unary(
                '/v1.ShioajiProvider/ListSettlements',
                request_serializer=provider__pb2.GetSettlementsRequest.SerializeToString,
                response_deserializer=provider__pb2.GetSettlementsResponse.FromString,
                _registered_method=True)
        self.GetMargin = channel.unary_unary(
                '/v1.ShioajiProvider/GetMargin',
                request_serializer=provider__pb2.GetMarginRequest.SerializeToString,
                response_deserializer=provider__pb2.Margin.FromString,
                _registered_method=True)
        self.GetTradingLimits = channel.unary_unary(
                '/v1.ShioajiProvider/GetTradingLimits',
                request_serializer=provider__pb2.GetTradingLimitsRequest.SerializeToString,
                response_deserializer=provider__pb2.TradingLimits.FromString,
                _registered_method=True)
        self.GetStockReserveSummary = channel.unary_unary(
                '/v1.ShioajiProvider/GetStockReserveSummary',
                request_serializer=provider__pb2.GetStockReserveSummaryRequest.SerializeToString,
                response_deserializer=provider__pb2.ReserveStocksSummaryResponse.FromString,
                _registered_method=True)
        self.GetStockReserveDetail = channel.unary_unary(
                '/v1.ShioajiProvider/GetStockReserveDetail',
                request_serializer=provider__pb2.GetStockReserveDetailRequest.SerializeToString,
                response_deserializer=provider__pb2.ReserveStocksDetailResponse.FromString,
                _registered_method=True)
        self.ReserveStock = channel.unary_unary(
                '/v1.ShioajiProvider/ReserveStock',
                request_serializer=provider__pb2.ReserveStockRequest.SerializeToString,
                response_deserializer=provider__pb2.ReserveStockResponse.FromString,
                _registered_method=True)
        self.GetEarmarkingDetail = channel.unary_unary(
                '/v1.ShioajiProvider/GetEarmarkingDetail',
                request_serializer=provider__pb2.GetEarmarkingDetailRequest.SerializeToString,
                response_deserializer=provider__pb2.EarmarkStocksDetailResponse.FromString,
                _registered_method=True)
        self.ReserveEarmarking = channel.unary_unary(
                '/v1.ShioajiProvider/ReserveEarmarking',
                request_serializer=provider__pb2.ReserveEarmarkingRequest.SerializeToString,
                response_deserializer=provider__pb2.ReserveEarmarkingResponse.FromString,
                _registered_method=True)
        self.GetSnapshots = channel.unary_unary(
                '/v1.ShioajiProvider/GetSnapshots',
                request_serializer=provider__pb2.GetSnapshotsRequest.SerializeToString,
                response_deserializer=provider__pb2.GetSnapshotsResponse.FromString,
                _registered_method=True)
        self.GetTicks = channel.unary_unary(
                '/v1.ShioajiProvider/GetTicks',
                request_serializer=provider__pb2.GetTicksRequest.SerializeToString,
                response_deserializer=provider__pb2.Ticks.FromString,
                _registered_method=True)
        self.GetKbars = channel.unary_unary(
                '/v1.ShioajiProvider/GetKbars',
                request_serializer=provider__pb2.GetKbarsRequest.SerializeToString,
                response_deserializer=provider__pb2.Kbars.FromString,
                _registered_method=True)
        self.GetDailyQuotes = channel.unary_unary(
                '/v1.ShioajiProvider/GetDailyQuotes',
                request_serializer=provider__pb2.GetDailyQuotesRequest.SerializeToString,
                response_deserializer=provider__pb2.DailyQuotes.FromString,
                _registered_method=True)
        self.CreditEnquires = channel.unary_unary(
                '/v1.ShioajiProvider/CreditEnquires',
                request_serializer=provider__pb2.CreditEnquiresRequest.SerializeToString,
                response_deserializer=provider__pb2.CreditEnquiresResponse.FromString,
                _registered_method=True)
        self.GetShortStockSources = channel.unary_unary(
                '/v1.ShioajiProvider/GetShortStockSources',
                request_serializer=provider__pb2.GetShortStockSourcesRequest.SerializeToString,
                response_deserializer=provider__pb2.GetShortStockSourcesResponse.FromString,
                _registered_method=True)
        self.GetScanners = channel.unary_unary(
                '/v1.ShioajiProvider/GetScanners',
                request_serializer=provider__pb2.GetScannersRequest.SerializeToString,
                response_deserializer=provider__pb2.GetScannersResponse.FromString,
                _registered_method=True)
        self.GetPunish = channel.unary_unary(
                '/v1.ShioajiProvider/GetPunish',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.Punish.FromString,
                _registered_method=True)
        self.GetNotice = channel.unary_unary(
                '/v1.ShioajiProvider/GetNotice',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.Notice.FromString,
                _registered_method=True)
        self.FetchContracts = channel.unary_unary(
                '/v1.ShioajiProvider/FetchContracts',
                request_serializer=provider__pb2.FetchContractsRequest.SerializeToString,
                response_deserializer=provider__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCAExpireTime = channel.unary_unary(
                '/v1.ShioajiProvider/GetCAExpireTime',
                request_serializer=provider__pb2.GetCAExpireTimeRequest.SerializeToString,
                response_deserializer=provider__pb2.GetCAExpireTimeResponse.FromString,
                _registered_method=True)
        self.SubscribeTrade = channel.unary_unary(
                '/v1.ShioajiProvider/SubscribeTrade',
                request_serializer=provider__pb2.SubscribeTradeRequest.SerializeToString,
                response_deserializer=provider__pb2.SubscribeTradeResponse.FromString,
                _registered_method=True)
        self.UnsubscribeTrade = channel.unary_unary(
                '/v1.ShioajiProvider/UnsubscribeTrade',
                request_serializer=provider__pb2.UnsubscribeTradeRequest.SerializeToString,
                response_deserializer=provider__pb2.UnsubscribeTradeResponse.FromString,
                _registered_method=True)


class ShioajiProviderServicer(object):
    """ShioajiProvider service provides a gRPC interface for trading and market data access
    using the Shioaji API (Taiwanese stock and futures trading).
    """

    def Login(self, request, context):
        """Login to the Shioaji API using API key and secret key.
        This initiates a session and fetches security contracts.
        登入
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout from the Shioaji API and terminate the current session.
        登出
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsage(self, request, context):
        """Retrieve usage information, including current connections and data consumption.
        使用量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccounts(self, request, context):
        """List all trading accounts associated with the logged-in user (e.g., Stock, Future, Option).
        帳號列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalance(self, request, context):
        """Get the account balance, including available balance and date.
        帳戶餘額
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Place a new order for a single contract.
        下單
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceComboOrder(self, request, context):
        """Place a combination order (e.g., multiple legs for futures or options).
        組合單下單
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrder(self, request, context):
        """Update an existing order (e.g., modify price or quantity).
        修改委託單
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Cancel an existing active order.
        撤銷委託單
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelComboOrder(self, request, context):
        """Cancel an active combination order.
        撤銷組合單委託
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Manually trigger an update for the status of orders and trades for a specific account.
        更新委託單狀態
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComboStatus(self, request, context):
        """Manually trigger an update for the status of combination orders for a specific account.
        更新組合單狀態
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrades(self, request, context):
        """List all trades (orders and their execution status) for the current session.
        委託列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListComboTrades(self, request, context):
        """List all combination trades for the current session.
        組合單委託列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderDealRecords(self, request, context):
        """Retrieve deal records for orders associated with a specific account.
        委託成交紀錄
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPositions(self, request, context):
        """List current open positions (unrealized profit and loss) for an account.
        查詢部位
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPositionDetail(self, request, context):
        """Get detailed information for a specific position.
        查詢部位詳細資訊
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfitLoss(self, request, context):
        """List realized profit and loss for a specific account within a date range.
        查詢損益
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfitLossDetail(self, request, context):
        """Get detailed realized profit and loss for a specific entry ID.
        查詢損益詳細資訊
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfitLossSummary(self, request, context):
        """Get a summary of realized profit and loss (buy cost, sell cost, pnl, etc.).
        查詢損益匯總
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSettlements(self, request, context):
        """Get settlement information for a stock account.
        查詢結算資訊
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSettlements(self, request, context):
        """Alias for GetSettlements.
        結算清單
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMargin(self, request, context):
        """Get margin information for a futures/options account.
        查詢保證金
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradingLimits(self, request, context):
        """Get trading limits (e.g., maximum daily volume) for a stock account.
        交易限額
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockReserveSummary(self, request, context):
        """Get a summary of stock reserve availability for borrowing.
        股票券源彙總
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockReserveDetail(self, request, context):
        """Get detailed information on stock reserve availability.
        股票券源明細
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveStock(self, request, context):
        """Request a reservation for borrowing stock shares.
        預約借券
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEarmarkingDetail(self, request, context):
        """Get details of earmarking (restricted funds for stock purchases).
        圈存明細
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveEarmarking(self, request, context):
        """Apply for earmarking shares at a specific price.
        預約圈存
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshots(self, request, context):
        """Get market snapshots (last price, volume, high, low) for a list of contract codes.
        行情快照
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTicks(self, request, context):
        """Get historical or real-time tick data for a contract on a specific date.
        獲取逐筆報價
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKbars(self, request, context):
        """Get K-bar (candlestick) data for a contract within a date range.
        獲取K線資料
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDailyQuotes(self, request, context):
        """Get daily trading quotes (summary) for all contracts on a specific date.
        每日報價
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreditEnquires(self, request, context):
        """Enquire about credit availability (margin/short) for a list of contracts.
        信用交易查詢
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShortStockSources(self, request, context):
        """Get available sources for shorting stock for a list of contracts.
        借券水源
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanners(self, request, context):
        """Run a market scanner to find stocks meeting specific ranking criteria.
        選股器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPunish(self, request, context):
        """Get information on disposition stocks (stocks under regulatory punishment).
        處置股
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotice(self, request, context):
        """Get information on attention stocks (notice stocks).
        注意股
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchContracts(self, request, context):
        """Manually fetch and update security contracts from the server.
        下載商品檔
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCAExpireTime(self, request, context):
        """Get the expiration timestamp of the currently activated CA.
        憑證過期時間
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTrade(self, request, context):
        """Subscribe to trade updates (execution reports) for an account.
        訂閱交易回報
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeTrade(self, request, context):
        """Unsubscribe from trade updates for an account.
        取消訂閱交易回報
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShioajiProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=provider__pb2.LoginRequest.FromString,
                    response_serializer=provider__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.LogoutResponse.SerializeToString,
            ),
            'GetUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsage,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.UsageStatus.SerializeToString,
            ),
            'ListAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccounts,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.ListAccountsResponse.SerializeToString,
            ),
            'GetAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalance,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.AccountBalance.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=provider__pb2.PlaceOrderRequest.FromString,
                    response_serializer=provider__pb2.Trade.SerializeToString,
            ),
            'PlaceComboOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceComboOrder,
                    request_deserializer=provider__pb2.PlaceComboOrderRequest.FromString,
                    response_serializer=provider__pb2.ComboTrade.SerializeToString,
            ),
            'UpdateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrder,
                    request_deserializer=provider__pb2.UpdateOrderRequest.FromString,
                    response_serializer=provider__pb2.Trade.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=provider__pb2.CancelOrderRequest.FromString,
                    response_serializer=provider__pb2.Trade.SerializeToString,
            ),
            'CancelComboOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelComboOrder,
                    request_deserializer=provider__pb2.CancelComboOrderRequest.FromString,
                    response_serializer=provider__pb2.ComboTrade.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=provider__pb2.UpdateStatusRequest.FromString,
                    response_serializer=provider__pb2.Empty.SerializeToString,
            ),
            'UpdateComboStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComboStatus,
                    request_deserializer=provider__pb2.UpdateStatusRequest.FromString,
                    response_serializer=provider__pb2.Empty.SerializeToString,
            ),
            'ListTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrades,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.ListTradesResponse.SerializeToString,
            ),
            'ListComboTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.ListComboTrades,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.ListComboTradesResponse.SerializeToString,
            ),
            'GetOrderDealRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderDealRecords,
                    request_deserializer=provider__pb2.GetOrderDealRecordsRequest.FromString,
                    response_serializer=provider__pb2.GetOrderDealRecordsResponse.SerializeToString,
            ),
            'ListPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPositions,
                    request_deserializer=provider__pb2.ListPositionsRequest.FromString,
                    response_serializer=provider__pb2.ListPositionsResponse.SerializeToString,
            ),
            'ListPositionDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPositionDetail,
                    request_deserializer=provider__pb2.ListPositionDetailRequest.FromString,
                    response_serializer=provider__pb2.ListPositionDetailResponse.SerializeToString,
            ),
            'ListProfitLoss': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfitLoss,
                    request_deserializer=provider__pb2.ListProfitLossRequest.FromString,
                    response_serializer=provider__pb2.ListProfitLossResponse.SerializeToString,
            ),
            'ListProfitLossDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfitLossDetail,
                    request_deserializer=provider__pb2.ListProfitLossDetailRequest.FromString,
                    response_serializer=provider__pb2.ListProfitLossDetailResponse.SerializeToString,
            ),
            'ListProfitLossSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfitLossSummary,
                    request_deserializer=provider__pb2.ListProfitLossSummaryRequest.FromString,
                    response_serializer=provider__pb2.ListProfitLossSummaryResponse.SerializeToString,
            ),
            'GetSettlements': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSettlements,
                    request_deserializer=provider__pb2.GetSettlementsRequest.FromString,
                    response_serializer=provider__pb2.GetSettlementsResponse.SerializeToString,
            ),
            'ListSettlements': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSettlements,
                    request_deserializer=provider__pb2.GetSettlementsRequest.FromString,
                    response_serializer=provider__pb2.GetSettlementsResponse.SerializeToString,
            ),
            'GetMargin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMargin,
                    request_deserializer=provider__pb2.GetMarginRequest.FromString,
                    response_serializer=provider__pb2.Margin.SerializeToString,
            ),
            'GetTradingLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradingLimits,
                    request_deserializer=provider__pb2.GetTradingLimitsRequest.FromString,
                    response_serializer=provider__pb2.TradingLimits.SerializeToString,
            ),
            'GetStockReserveSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockReserveSummary,
                    request_deserializer=provider__pb2.GetStockReserveSummaryRequest.FromString,
                    response_serializer=provider__pb2.ReserveStocksSummaryResponse.SerializeToString,
            ),
            'GetStockReserveDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockReserveDetail,
                    request_deserializer=provider__pb2.GetStockReserveDetailRequest.FromString,
                    response_serializer=provider__pb2.ReserveStocksDetailResponse.SerializeToString,
            ),
            'ReserveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStock,
                    request_deserializer=provider__pb2.ReserveStockRequest.FromString,
                    response_serializer=provider__pb2.ReserveStockResponse.SerializeToString,
            ),
            'GetEarmarkingDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEarmarkingDetail,
                    request_deserializer=provider__pb2.GetEarmarkingDetailRequest.FromString,
                    response_serializer=provider__pb2.EarmarkStocksDetailResponse.SerializeToString,
            ),
            'ReserveEarmarking': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveEarmarking,
                    request_deserializer=provider__pb2.ReserveEarmarkingRequest.FromString,
                    response_serializer=provider__pb2.ReserveEarmarkingResponse.SerializeToString,
            ),
            'GetSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshots,
                    request_deserializer=provider__pb2.GetSnapshotsRequest.FromString,
                    response_serializer=provider__pb2.GetSnapshotsResponse.SerializeToString,
            ),
            'GetTicks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicks,
                    request_deserializer=provider__pb2.GetTicksRequest.FromString,
                    response_serializer=provider__pb2.Ticks.SerializeToString,
            ),
            'GetKbars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKbars,
                    request_deserializer=provider__pb2.GetKbarsRequest.FromString,
                    response_serializer=provider__pb2.Kbars.SerializeToString,
            ),
            'GetDailyQuotes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDailyQuotes,
                    request_deserializer=provider__pb2.GetDailyQuotesRequest.FromString,
                    response_serializer=provider__pb2.DailyQuotes.SerializeToString,
            ),
            'CreditEnquires': grpc.unary_unary_rpc_method_handler(
                    servicer.CreditEnquires,
                    request_deserializer=provider__pb2.CreditEnquiresRequest.FromString,
                    response_serializer=provider__pb2.CreditEnquiresResponse.SerializeToString,
            ),
            'GetShortStockSources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShortStockSources,
                    request_deserializer=provider__pb2.GetShortStockSourcesRequest.FromString,
                    response_serializer=provider__pb2.GetShortStockSourcesResponse.SerializeToString,
            ),
            'GetScanners': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanners,
                    request_deserializer=provider__pb2.GetScannersRequest.FromString,
                    response_serializer=provider__pb2.GetScannersResponse.SerializeToString,
            ),
            'GetPunish': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPunish,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.Punish.SerializeToString,
            ),
            'GetNotice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotice,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.Notice.SerializeToString,
            ),
            'FetchContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchContracts,
                    request_deserializer=provider__pb2.FetchContractsRequest.FromString,
                    response_serializer=provider__pb2.Empty.SerializeToString,
            ),
            'GetCAExpireTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCAExpireTime,
                    request_deserializer=provider__pb2.GetCAExpireTimeRequest.FromString,
                    response_serializer=provider__pb2.GetCAExpireTimeResponse.SerializeToString,
            ),
            'SubscribeTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeTrade,
                    request_deserializer=provider__pb2.SubscribeTradeRequest.FromString,
                    response_serializer=provider__pb2.SubscribeTradeResponse.SerializeToString,
            ),
            'UnsubscribeTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeTrade,
                    request_deserializer=provider__pb2.UnsubscribeTradeRequest.FromString,
                    response_serializer=provider__pb2.UnsubscribeTradeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.ShioajiProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.ShioajiProvider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShioajiProvider(object):
    """ShioajiProvider service provides a gRPC interface for trading and market data access
    using the Shioaji API (Taiwanese stock and futures trading).
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/Login',
            provider__pb2.LoginRequest.SerializeToString,
            provider__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/Logout',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetUsage',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.UsageStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListAccounts',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.ListAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetAccountBalance',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.AccountBalance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/PlaceOrder',
            provider__pb2.PlaceOrderRequest.SerializeToString,
            provider__pb2.Trade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceComboOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/PlaceComboOrder',
            provider__pb2.PlaceComboOrderRequest.SerializeToString,
            provider__pb2.ComboTrade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/UpdateOrder',
            provider__pb2.UpdateOrderRequest.SerializeToString,
            provider__pb2.Trade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/CancelOrder',
            provider__pb2.CancelOrderRequest.SerializeToString,
            provider__pb2.Trade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelComboOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/CancelComboOrder',
            provider__pb2.CancelComboOrderRequest.SerializeToString,
            provider__pb2.ComboTrade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/UpdateStatus',
            provider__pb2.UpdateStatusRequest.SerializeToString,
            provider__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComboStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/UpdateComboStatus',
            provider__pb2.UpdateStatusRequest.SerializeToString,
            provider__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListTrades',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.ListTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListComboTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListComboTrades',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.ListComboTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderDealRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetOrderDealRecords',
            provider__pb2.GetOrderDealRecordsRequest.SerializeToString,
            provider__pb2.GetOrderDealRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListPositions',
            provider__pb2.ListPositionsRequest.SerializeToString,
            provider__pb2.ListPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPositionDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListPositionDetail',
            provider__pb2.ListPositionDetailRequest.SerializeToString,
            provider__pb2.ListPositionDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfitLoss(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListProfitLoss',
            provider__pb2.ListProfitLossRequest.SerializeToString,
            provider__pb2.ListProfitLossResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfitLossDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListProfitLossDetail',
            provider__pb2.ListProfitLossDetailRequest.SerializeToString,
            provider__pb2.ListProfitLossDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfitLossSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListProfitLossSummary',
            provider__pb2.ListProfitLossSummaryRequest.SerializeToString,
            provider__pb2.ListProfitLossSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSettlements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetSettlements',
            provider__pb2.GetSettlementsRequest.SerializeToString,
            provider__pb2.GetSettlementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSettlements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListSettlements',
            provider__pb2.GetSettlementsRequest.SerializeToString,
            provider__pb2.GetSettlementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMargin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetMargin',
            provider__pb2.GetMarginRequest.SerializeToString,
            provider__pb2.Margin.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradingLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetTradingLimits',
            provider__pb2.GetTradingLimitsRequest.SerializeToString,
            provider__pb2.TradingLimits.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockReserveSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetStockReserveSummary',
            provider__pb2.GetStockReserveSummaryRequest.SerializeToString,
            provider__pb2.ReserveStocksSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockReserveDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetStockReserveDetail',
            provider__pb2.GetStockReserveDetailRequest.SerializeToString,
            provider__pb2.ReserveStocksDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ReserveStock',
            provider__pb2.ReserveStockRequest.SerializeToString,
            provider__pb2.ReserveStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEarmarkingDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetEarmarkingDetail',
            provider__pb2.GetEarmarkingDetailRequest.SerializeToString,
            provider__pb2.EarmarkStocksDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveEarmarking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ReserveEarmarking',
            provider__pb2.ReserveEarmarkingRequest.SerializeToString,
            provider__pb2.ReserveEarmarkingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetSnapshots',
            provider__pb2.GetSnapshotsRequest.SerializeToString,
            provider__pb2.GetSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTicks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetTicks',
            provider__pb2.GetTicksRequest.SerializeToString,
            provider__pb2.Ticks.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKbars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetKbars',
            provider__pb2.GetKbarsRequest.SerializeToString,
            provider__pb2.Kbars.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDailyQuotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetDailyQuotes',
            provider__pb2.GetDailyQuotesRequest.SerializeToString,
            provider__pb2.DailyQuotes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreditEnquires(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/CreditEnquires',
            provider__pb2.CreditEnquiresRequest.SerializeToString,
            provider__pb2.CreditEnquiresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShortStockSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetShortStockSources',
            provider__pb2.GetShortStockSourcesRequest.SerializeToString,
            provider__pb2.GetShortStockSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanners(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetScanners',
            provider__pb2.GetScannersRequest.SerializeToString,
            provider__pb2.GetScannersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPunish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetPunish',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.Punish.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNotice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetNotice',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.Notice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/FetchContracts',
            provider__pb2.FetchContractsRequest.SerializeToString,
            provider__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCAExpireTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetCAExpireTime',
            provider__pb2.GetCAExpireTimeRequest.SerializeToString,
            provider__pb2.GetCAExpireTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/SubscribeTrade',
            provider__pb2.SubscribeTradeRequest.SerializeToString,
            provider__pb2.SubscribeTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/UnsubscribeTrade',
            provider__pb2.UnsubscribeTradeRequest.SerializeToString,
            provider__pb2.UnsubscribeTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
