# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import provider_pb2 as provider__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in provider_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShioajiProviderStub(object):
    """Service Definition
    ShioajiProvider service provides an interface for trading and market data access.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/v1.ShioajiProvider/Login',
                request_serializer=provider__pb2.LoginRequest.SerializeToString,
                response_deserializer=provider__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.ListAccounts = channel.unary_unary(
                '/v1.ShioajiProvider/ListAccounts',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.ListAccountsResponse.FromString,
                _registered_method=True)
        self.GetAccountBalance = channel.unary_unary(
                '/v1.ShioajiProvider/GetAccountBalance',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.AccountBalanceResponse.FromString,
                _registered_method=True)
        self.ListSettlements = channel.unary_unary(
                '/v1.ShioajiProvider/ListSettlements',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.ListSettlementsResponse.FromString,
                _registered_method=True)
        self.ListProfitLoss = channel.unary_unary(
                '/v1.ShioajiProvider/ListProfitLoss',
                request_serializer=provider__pb2.ListProfitLossRequest.SerializeToString,
                response_deserializer=provider__pb2.ListProfitLossResponse.FromString,
                _registered_method=True)
        self.ListPositions = channel.unary_unary(
                '/v1.ShioajiProvider/ListPositions',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.ListPositionsResponse.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/v1.ShioajiProvider/PlaceOrder',
                request_serializer=provider__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=provider__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.UpdateOrder = channel.unary_unary(
                '/v1.ShioajiProvider/UpdateOrder',
                request_serializer=provider__pb2.UpdateOrderRequest.SerializeToString,
                response_deserializer=provider__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/v1.ShioajiProvider/CancelOrder',
                request_serializer=provider__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=provider__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.ListTrades = channel.unary_unary(
                '/v1.ShioajiProvider/ListTrades',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.ListTradesResponse.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/v1.ShioajiProvider/UpdateStatus',
                request_serializer=provider__pb2.Empty.SerializeToString,
                response_deserializer=provider__pb2.Empty.FromString,
                _registered_method=True)
        self.GetTicks = channel.unary_unary(
                '/v1.ShioajiProvider/GetTicks',
                request_serializer=provider__pb2.GetTicksRequest.SerializeToString,
                response_deserializer=provider__pb2.GetTicksResponse.FromString,
                _registered_method=True)
        self.GetKbars = channel.unary_unary(
                '/v1.ShioajiProvider/GetKbars',
                request_serializer=provider__pb2.GetKbarsRequest.SerializeToString,
                response_deserializer=provider__pb2.GetKbarsResponse.FromString,
                _registered_method=True)
        self.GetSnapshots = channel.unary_unary(
                '/v1.ShioajiProvider/GetSnapshots',
                request_serializer=provider__pb2.GetSnapshotsRequest.SerializeToString,
                response_deserializer=provider__pb2.GetSnapshotsResponse.FromString,
                _registered_method=True)
        self.SubscribeQuote = channel.unary_unary(
                '/v1.ShioajiProvider/SubscribeQuote',
                request_serializer=provider__pb2.SubscribeQuoteRequest.SerializeToString,
                response_deserializer=provider__pb2.Empty.FromString,
                _registered_method=True)
        self.UnsubscribeQuote = channel.unary_unary(
                '/v1.ShioajiProvider/UnsubscribeQuote',
                request_serializer=provider__pb2.UnsubscribeQuoteRequest.SerializeToString,
                response_deserializer=provider__pb2.Empty.FromString,
                _registered_method=True)


class ShioajiProviderServicer(object):
    """Service Definition
    ShioajiProvider service provides an interface for trading and market data access.
    """

    def Login(self, request, context):
        """Authenticates the user and establishes a connection with the Shioaji API.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccounts(self, request, context):
        """Retrieves all available trading accounts for the logged-in user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalance(self, request, context):
        """Queries the current balance for the default stock account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSettlements(self, request, context):
        """Retrieves stock account settlement details.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfitLoss(self, request, context):
        """Queries realized profit and loss for a specified date range.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPositions(self, request, context):
        """Retrieves current unrealized positions and their profit/loss.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Submits a new trading order for a specific contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrder(self, request, context):
        """Modifies the price or quantity of an existing active order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Requests the cancellation of an existing active order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrades(self, request, context):
        """Lists all active trades and their statuses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Forces an update of order and trade statuses for the current session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTicks(self, request, context):
        """Retrieves historical tick data for a contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKbars(self, request, context):
        """Retrieves historical candlestick (K-bar) data for a contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshots(self, request, context):
        """Retrieves current market snapshots for one or more contracts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeQuote(self, request, context):
        """Subscribes to real-time market data (ticks or quotes) for a contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeQuote(self, request, context):
        """Unsubscribes from real-time market data updates for a contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShioajiProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=provider__pb2.LoginRequest.FromString,
                    response_serializer=provider__pb2.LoginResponse.SerializeToString,
            ),
            'ListAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccounts,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.ListAccountsResponse.SerializeToString,
            ),
            'GetAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalance,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.AccountBalanceResponse.SerializeToString,
            ),
            'ListSettlements': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSettlements,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.ListSettlementsResponse.SerializeToString,
            ),
            'ListProfitLoss': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfitLoss,
                    request_deserializer=provider__pb2.ListProfitLossRequest.FromString,
                    response_serializer=provider__pb2.ListProfitLossResponse.SerializeToString,
            ),
            'ListPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPositions,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.ListPositionsResponse.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=provider__pb2.PlaceOrderRequest.FromString,
                    response_serializer=provider__pb2.TradeResponse.SerializeToString,
            ),
            'UpdateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrder,
                    request_deserializer=provider__pb2.UpdateOrderRequest.FromString,
                    response_serializer=provider__pb2.TradeResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=provider__pb2.CancelOrderRequest.FromString,
                    response_serializer=provider__pb2.TradeResponse.SerializeToString,
            ),
            'ListTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrades,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.ListTradesResponse.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=provider__pb2.Empty.FromString,
                    response_serializer=provider__pb2.Empty.SerializeToString,
            ),
            'GetTicks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicks,
                    request_deserializer=provider__pb2.GetTicksRequest.FromString,
                    response_serializer=provider__pb2.GetTicksResponse.SerializeToString,
            ),
            'GetKbars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKbars,
                    request_deserializer=provider__pb2.GetKbarsRequest.FromString,
                    response_serializer=provider__pb2.GetKbarsResponse.SerializeToString,
            ),
            'GetSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshots,
                    request_deserializer=provider__pb2.GetSnapshotsRequest.FromString,
                    response_serializer=provider__pb2.GetSnapshotsResponse.SerializeToString,
            ),
            'SubscribeQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.SubscribeQuote,
                    request_deserializer=provider__pb2.SubscribeQuoteRequest.FromString,
                    response_serializer=provider__pb2.Empty.SerializeToString,
            ),
            'UnsubscribeQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeQuote,
                    request_deserializer=provider__pb2.UnsubscribeQuoteRequest.FromString,
                    response_serializer=provider__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.ShioajiProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1.ShioajiProvider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShioajiProvider(object):
    """Service Definition
    ShioajiProvider service provides an interface for trading and market data access.
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/Login',
            provider__pb2.LoginRequest.SerializeToString,
            provider__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListAccounts',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.ListAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetAccountBalance',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.AccountBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSettlements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListSettlements',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.ListSettlementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfitLoss(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListProfitLoss',
            provider__pb2.ListProfitLossRequest.SerializeToString,
            provider__pb2.ListProfitLossResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListPositions',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.ListPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/PlaceOrder',
            provider__pb2.PlaceOrderRequest.SerializeToString,
            provider__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/UpdateOrder',
            provider__pb2.UpdateOrderRequest.SerializeToString,
            provider__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/CancelOrder',
            provider__pb2.CancelOrderRequest.SerializeToString,
            provider__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/ListTrades',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.ListTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/UpdateStatus',
            provider__pb2.Empty.SerializeToString,
            provider__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTicks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetTicks',
            provider__pb2.GetTicksRequest.SerializeToString,
            provider__pb2.GetTicksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKbars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetKbars',
            provider__pb2.GetKbarsRequest.SerializeToString,
            provider__pb2.GetKbarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/GetSnapshots',
            provider__pb2.GetSnapshotsRequest.SerializeToString,
            provider__pb2.GetSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/SubscribeQuote',
            provider__pb2.SubscribeQuoteRequest.SerializeToString,
            provider__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1.ShioajiProvider/UnsubscribeQuote',
            provider__pb2.UnsubscribeQuoteRequest.SerializeToString,
            provider__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
