// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ca/activate": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Activate the Certificate Authority for the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Activate CA",
                "parameters": [
                    {
                        "description": "CA Activation Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/phoenix_processor_pkg_pb.ActivateCARequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/phoenix_processor_pkg_pb.ActivateCAResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/ca/expire": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve the expiration time of the user's Certificate Authority",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get CA Expire Time",
                "parameters": [
                    {
                        "description": "CA Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/phoenix_processor_pkg_pb.GetCAExpireTimeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/phoenix_processor_pkg_pb.GetCAExpireTimeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.APIError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.APIError"
                        }
                    }
                }
            }
        },
        "/api/v1/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Invalidate the session (placeholder for now)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/phoenix_processor_pkg_pb.LogoutResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_gateway_handler.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_gateway_handler.APIError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "phoenix_processor_pkg_pb.ActivateCARequest": {
            "type": "object",
            "properties": {
                "ca_passwd": {
                    "description": "CA password.",
                    "type": "string"
                },
                "ca_path": {
                    "description": "File path to CA.",
                    "type": "string"
                },
                "person_id": {
                    "description": "Holder's person ID.",
                    "type": "string"
                }
            }
        },
        "phoenix_processor_pkg_pb.ActivateCAResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "phoenix_processor_pkg_pb.GetCAExpireTimeRequest": {
            "type": "object",
            "properties": {
                "person_id": {
                    "type": "string"
                }
            }
        },
        "phoenix_processor_pkg_pb.GetCAExpireTimeResponse": {
            "type": "object",
            "properties": {
                "expire_time": {
                    "type": "string"
                }
            }
        },
        "phoenix_processor_pkg_pb.LogoutResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "description": "True if logout was successful.",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and then your token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Phoenix API",
	Description:      "REST API Gateway for Shioaji Trading Provider.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
