// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: provider.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trading account information including account type, person ID, broker ID, account ID, and signed status.
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountType   string                 `protobuf:"bytes,1,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	BrokerId      string                 `protobuf:"bytes,3,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Signed        bool                   `protobuf:"varint,5,opt,name=signed,proto3" json:"signed,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *Account) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetSigned() bool {
	if x != nil {
		return x.Signed
	}
	return false
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Detailed contract information for various instruments like stocks, futures, options, and indices.
type Contract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecurityType  string                 `protobuf:"bytes,1,opt,name=security_type,json=securityType,proto3" json:"security_type,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	LimitUp       float64                `protobuf:"fixed64,7,opt,name=limit_up,json=limitUp,proto3" json:"limit_up,omitempty"`
	LimitDown     float64                `protobuf:"fixed64,8,opt,name=limit_down,json=limitDown,proto3" json:"limit_down,omitempty"`
	Reference     float64                `protobuf:"fixed64,9,opt,name=reference,proto3" json:"reference,omitempty"`
	UpdateDate    string                 `protobuf:"bytes,10,opt,name=update_date,json=updateDate,proto3" json:"update_date,omitempty"`
	DayTrade      string                 `protobuf:"bytes,11,opt,name=day_trade,json=dayTrade,proto3" json:"day_trade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *Contract) GetSecurityType() string {
	if x != nil {
		return x.SecurityType
	}
	return ""
}

func (x *Contract) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Contract) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Contract) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Contract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contract) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Contract) GetLimitUp() float64 {
	if x != nil {
		return x.LimitUp
	}
	return 0
}

func (x *Contract) GetLimitDown() float64 {
	if x != nil {
		return x.LimitDown
	}
	return 0
}

func (x *Contract) GetReference() float64 {
	if x != nil {
		return x.Reference
	}
	return 0
}

func (x *Contract) GetUpdateDate() string {
	if x != nil {
		return x.UpdateDate
	}
	return ""
}

func (x *Contract) GetDayTrade() string {
	if x != nil {
		return x.DayTrade
	}
	return ""
}

// Trading order details including action, price, quantity, and order type.
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceType     string                 `protobuf:"bytes,4,opt,name=price_type,json=priceType,proto3" json:"price_type,omitempty"`
	OrderType     string                 `protobuf:"bytes,5,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	OrderLot      string                 `protobuf:"bytes,6,opt,name=order_lot,json=orderLot,proto3" json:"order_lot,omitempty"`
	OrderCond     string                 `protobuf:"bytes,7,opt,name=order_cond,json=orderCond,proto3" json:"order_cond,omitempty"`
	Id            string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	Seqno         string                 `protobuf:"bytes,9,opt,name=seqno,proto3" json:"seqno,omitempty"`
	Ordno         string                 `protobuf:"bytes,10,opt,name=ordno,proto3" json:"ordno,omitempty"`
	Account       *Account               `protobuf:"bytes,11,opt,name=account,proto3" json:"account,omitempty"`
	CustomField   string                 `protobuf:"bytes,12,opt,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetPriceType() string {
	if x != nil {
		return x.PriceType
	}
	return ""
}

func (x *Order) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *Order) GetOrderLot() string {
	if x != nil {
		return x.OrderLot
	}
	return ""
}

func (x *Order) GetOrderCond() string {
	if x != nil {
		return x.OrderCond
	}
	return ""
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetSeqno() string {
	if x != nil {
		return x.Seqno
	}
	return ""
}

func (x *Order) GetOrdno() string {
	if x != nil {
		return x.Ordno
	}
	return ""
}

func (x *Order) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Order) GetCustomField() string {
	if x != nil {
		return x.CustomField
	}
	return ""
}

// Information about placed trading orders and their execution status.
type Trade struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // Order ID
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // e.g., PendingSubmit, Filled
	StatusCode        string                 `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	OrderTs           int64                  `protobuf:"varint,4,opt,name=order_ts,json=orderTs,proto3" json:"order_ts,omitempty"`
	Msg               string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	Price             float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity          int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	FilledQuantity    int64                  `protobuf:"varint,8,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	CancelledQuantity int64                  `protobuf:"varint,9,opt,name=cancelled_quantity,json=cancelledQuantity,proto3" json:"cancelled_quantity,omitempty"`
	Ordno             string                 `protobuf:"bytes,10,opt,name=ordno,proto3" json:"ordno,omitempty"`
	Contract          *Contract              `protobuf:"bytes,11,opt,name=contract,proto3" json:"contract,omitempty"`
	Order             *Order                 `protobuf:"bytes,12,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Trade) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Trade) GetOrderTs() int64 {
	if x != nil {
		return x.OrderTs
	}
	return 0
}

func (x *Trade) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetFilledQuantity() int64 {
	if x != nil {
		return x.FilledQuantity
	}
	return 0
}

func (x *Trade) GetCancelledQuantity() int64 {
	if x != nil {
		return x.CancelledQuantity
	}
	return 0
}

func (x *Trade) GetOrdno() string {
	if x != nil {
		return x.Ordno
	}
	return ""
}

func (x *Trade) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *Trade) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// Real-time or historical tick data for a contract, including price and volume.
type Tick struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Datetime        string                 `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Open            float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	AvgPrice        float64                `protobuf:"fixed64,4,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Close           float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	High            float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`
	Low             float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`
	Amount          float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	TotalAmount     float64                `protobuf:"fixed64,9,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Volume          int64                  `protobuf:"varint,10,opt,name=volume,proto3" json:"volume,omitempty"`
	TotalVolume     int64                  `protobuf:"varint,11,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	TickType        int32                  `protobuf:"varint,12,opt,name=tick_type,json=tickType,proto3" json:"tick_type,omitempty"`
	ChgType         int32                  `protobuf:"varint,13,opt,name=chg_type,json=chgType,proto3" json:"chg_type,omitempty"`
	PriceChg        float64                `protobuf:"fixed64,14,opt,name=price_chg,json=priceChg,proto3" json:"price_chg,omitempty"`
	PctChg          float64                `protobuf:"fixed64,15,opt,name=pct_chg,json=pctChg,proto3" json:"pct_chg,omitempty"`
	BidSideTotalVol int64                  `protobuf:"varint,16,opt,name=bid_side_total_vol,json=bidSideTotalVol,proto3" json:"bid_side_total_vol,omitempty"`
	AskSideTotalVol int64                  `protobuf:"varint,17,opt,name=ask_side_total_vol,json=askSideTotalVol,proto3" json:"ask_side_total_vol,omitempty"`
	Simtrade        bool                   `protobuf:"varint,18,opt,name=simtrade,proto3" json:"simtrade,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{4}
}

func (x *Tick) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Tick) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *Tick) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Tick) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *Tick) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Tick) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Tick) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Tick) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Tick) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Tick) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Tick) GetTotalVolume() int64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *Tick) GetTickType() int32 {
	if x != nil {
		return x.TickType
	}
	return 0
}

func (x *Tick) GetChgType() int32 {
	if x != nil {
		return x.ChgType
	}
	return 0
}

func (x *Tick) GetPriceChg() float64 {
	if x != nil {
		return x.PriceChg
	}
	return 0
}

func (x *Tick) GetPctChg() float64 {
	if x != nil {
		return x.PctChg
	}
	return 0
}

func (x *Tick) GetBidSideTotalVol() int64 {
	if x != nil {
		return x.BidSideTotalVol
	}
	return 0
}

func (x *Tick) GetAskSideTotalVol() int64 {
	if x != nil {
		return x.AskSideTotalVol
	}
	return 0
}

func (x *Tick) GetSimtrade() bool {
	if x != nil {
		return x.Simtrade
	}
	return false
}

// Historical candlestick (K-bar) data including open, high, low, close prices, and volume.
type Kbar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        int64                  `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kbar) Reset() {
	*x = Kbar{}
	mi := &file_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kbar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kbar) ProtoMessage() {}

func (x *Kbar) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kbar.ProtoReflect.Descriptor instead.
func (*Kbar) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{5}
}

func (x *Kbar) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Kbar) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Kbar) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Kbar) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Kbar) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Kbar) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Kbar) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Real-time market snapshot for a contract, providing a summary of current market conditions.
type Snapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ts                 int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Code               string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Exchange           string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Open               float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High               float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low                float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close              float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
	AveragePrice       float64                `protobuf:"fixed64,8,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	Volume             int64                  `protobuf:"varint,9,opt,name=volume,proto3" json:"volume,omitempty"`
	TotalVolume        int64                  `protobuf:"varint,10,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	Amount             float64                `protobuf:"fixed64,11,opt,name=amount,proto3" json:"amount,omitempty"`
	TotalAmount        float64                `protobuf:"fixed64,12,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PriceChange        float64                `protobuf:"fixed64,13,opt,name=price_change,json=priceChange,proto3" json:"price_change,omitempty"`
	PriceChangePercent float64                `protobuf:"fixed64,14,opt,name=price_change_percent,json=priceChangePercent,proto3" json:"price_change_percent,omitempty"`
	BuyPrice           float64                `protobuf:"fixed64,15,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	BuyVolume          int64                  `protobuf:"varint,16,opt,name=buy_volume,json=buyVolume,proto3" json:"buy_volume,omitempty"`
	SellPrice          float64                `protobuf:"fixed64,17,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	SellVolume         int64                  `protobuf:"varint,18,opt,name=sell_volume,json=sellVolume,proto3" json:"sell_volume,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{6}
}

func (x *Snapshot) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Snapshot) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Snapshot) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Snapshot) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Snapshot) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Snapshot) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Snapshot) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Snapshot) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

func (x *Snapshot) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Snapshot) GetTotalVolume() int64 {
	if x != nil {
		return x.TotalVolume
	}
	return 0
}

func (x *Snapshot) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Snapshot) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Snapshot) GetPriceChange() float64 {
	if x != nil {
		return x.PriceChange
	}
	return 0
}

func (x *Snapshot) GetPriceChangePercent() float64 {
	if x != nil {
		return x.PriceChangePercent
	}
	return 0
}

func (x *Snapshot) GetBuyPrice() float64 {
	if x != nil {
		return x.BuyPrice
	}
	return 0
}

func (x *Snapshot) GetBuyVolume() int64 {
	if x != nil {
		return x.BuyVolume
	}
	return 0
}

func (x *Snapshot) GetSellPrice() float64 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *Snapshot) GetSellVolume() int64 {
	if x != nil {
		return x.SellVolume
	}
	return 0
}

// Realized profit and loss for a specific trade or period.
type ProfitLoss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Seqno         string                 `protobuf:"bytes,3,opt,name=seqno,proto3" json:"seqno,omitempty"`
	Dseq          string                 `protobuf:"bytes,4,opt,name=dseq,proto3" json:"dseq,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Pnl           float64                `protobuf:"fixed64,7,opt,name=pnl,proto3" json:"pnl,omitempty"`
	PrRatio       float64                `protobuf:"fixed64,8,opt,name=pr_ratio,json=prRatio,proto3" json:"pr_ratio,omitempty"`
	Cond          string                 `protobuf:"bytes,9,opt,name=cond,proto3" json:"cond,omitempty"`
	Date          string                 `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfitLoss) Reset() {
	*x = ProfitLoss{}
	mi := &file_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitLoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitLoss) ProtoMessage() {}

func (x *ProfitLoss) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitLoss.ProtoReflect.Descriptor instead.
func (*ProfitLoss) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ProfitLoss) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProfitLoss) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProfitLoss) GetSeqno() string {
	if x != nil {
		return x.Seqno
	}
	return ""
}

func (x *ProfitLoss) GetDseq() string {
	if x != nil {
		return x.Dseq
	}
	return ""
}

func (x *ProfitLoss) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProfitLoss) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProfitLoss) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

func (x *ProfitLoss) GetPrRatio() float64 {
	if x != nil {
		return x.PrRatio
	}
	return 0
}

func (x *ProfitLoss) GetCond() string {
	if x != nil {
		return x.Cond
	}
	return ""
}

func (x *ProfitLoss) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Stock account settlement details, including date and amount.
type Settlement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TTime         string                 `protobuf:"bytes,3,opt,name=t_time,json=tTime,proto3" json:"t_time,omitempty"` // "T" or "T+1" etc, renamed to avoid conflict
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settlement) Reset() {
	*x = Settlement{}
	mi := &file_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settlement) ProtoMessage() {}

func (x *Settlement) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settlement.ProtoReflect.Descriptor instead.
func (*Settlement) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{8}
}

func (x *Settlement) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Settlement) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Settlement) GetTTime() string {
	if x != nil {
		return x.TTime
	}
	return ""
}

// Unrealized gain or loss for currently held positions.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,6,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Pnl           float64                `protobuf:"fixed64,7,opt,name=pnl,proto3" json:"pnl,omitempty"`
	Cond          string                 `protobuf:"bytes,8,opt,name=cond,proto3" json:"cond,omitempty"`
	OrderType     string                 `protobuf:"bytes,9,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`  // e.g., ROD
	PriceType     string                 `protobuf:"bytes,10,opt,name=price_type,json=priceType,proto3" json:"price_type,omitempty"` // e.g., LMT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{9}
}

func (x *Position) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Position) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Position) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Position) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Position) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Position) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *Position) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

func (x *Position) GetCond() string {
	if x != nil {
		return x.Cond
	}
	return ""
}

func (x *Position) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *Position) GetPriceType() string {
	if x != nil {
		return x.PriceType
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{10}
}

// Request message for Login method.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Passwd        string                 `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{11}
}

func (x *LoginRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *LoginRequest) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

func (x *LoginRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *LoginRequest) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

// Response message for Login method.
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{12}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Response message for ListAccounts method.
type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{13}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

// Response message for GetAccountBalance method.
type AccountBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       float64                `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBalanceResponse) Reset() {
	*x = AccountBalanceResponse{}
	mi := &file_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalanceResponse) ProtoMessage() {}

func (x *AccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*AccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{14}
}

func (x *AccountBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Response message for ListSettlements method.
type ListSettlementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settlements   []*Settlement          `protobuf:"bytes,1,rep,name=settlements,proto3" json:"settlements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSettlementsResponse) Reset() {
	*x = ListSettlementsResponse{}
	mi := &file_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSettlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSettlementsResponse) ProtoMessage() {}

func (x *ListSettlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSettlementsResponse.ProtoReflect.Descriptor instead.
func (*ListSettlementsResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{15}
}

func (x *ListSettlementsResponse) GetSettlements() []*Settlement {
	if x != nil {
		return x.Settlements
	}
	return nil
}

// Request message for ListProfitLoss method.
type ListProfitLossRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeginDate     string                 `protobuf:"bytes,1,opt,name=begin_date,json=beginDate,proto3" json:"begin_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfitLossRequest) Reset() {
	*x = ListProfitLossRequest{}
	mi := &file_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfitLossRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfitLossRequest) ProtoMessage() {}

func (x *ListProfitLossRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfitLossRequest.ProtoReflect.Descriptor instead.
func (*ListProfitLossRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{16}
}

func (x *ListProfitLossRequest) GetBeginDate() string {
	if x != nil {
		return x.BeginDate
	}
	return ""
}

func (x *ListProfitLossRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Response message for ListProfitLoss method.
type ListProfitLossResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfitLoss    []*ProfitLoss          `protobuf:"bytes,1,rep,name=profit_loss,json=profitLoss,proto3" json:"profit_loss,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfitLossResponse) Reset() {
	*x = ListProfitLossResponse{}
	mi := &file_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfitLossResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfitLossResponse) ProtoMessage() {}

func (x *ListProfitLossResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfitLossResponse.ProtoReflect.Descriptor instead.
func (*ListProfitLossResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{17}
}

func (x *ListProfitLossResponse) GetProfitLoss() []*ProfitLoss {
	if x != nil {
		return x.ProfitLoss
	}
	return nil
}

// Response message for ListPositions method.
type ListPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsResponse) Reset() {
	*x = ListPositionsResponse{}
	mi := &file_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsResponse) ProtoMessage() {}

func (x *ListPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsResponse.ProtoReflect.Descriptor instead.
func (*ListPositionsResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{18}
}

func (x *ListPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// Request message for PlaceOrder method.
type PlaceOrderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContractCode         string                 `protobuf:"bytes,1,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	ContractSecurityType string                 `protobuf:"bytes,2,opt,name=contract_security_type,json=contractSecurityType,proto3" json:"contract_security_type,omitempty"` // e.g., "STK", "FUT"
	Action               string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                                           // "Buy", "Sell"
	Price                float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceType            string                 `protobuf:"bytes,6,opt,name=price_type,json=priceType,proto3" json:"price_type,omitempty"` // "LMT", "MKT"
	OrderType            string                 `protobuf:"bytes,7,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // "ROD", "IOC", "FOK"
	OrderLot             string                 `protobuf:"bytes,8,opt,name=order_lot,json=orderLot,proto3" json:"order_lot,omitempty"`    // "Common", "IntradayOdd"
	AccountId            string                 `protobuf:"bytes,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // Optional, to specify account
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{19}
}

func (x *PlaceOrderRequest) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *PlaceOrderRequest) GetContractSecurityType() string {
	if x != nil {
		return x.ContractSecurityType
	}
	return ""
}

func (x *PlaceOrderRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlaceOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PlaceOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PlaceOrderRequest) GetPriceType() string {
	if x != nil {
		return x.PriceType
	}
	return ""
}

func (x *PlaceOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *PlaceOrderRequest) GetOrderLot() string {
	if x != nil {
		return x.OrderLot
	}
	return ""
}

func (x *PlaceOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Request message for UpdateOrder method.
type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateOrderRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *UpdateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Request message for CancelOrder method.
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{21}
}

func (x *CancelOrderRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

// Response message for PlaceOrder, UpdateOrder, and CancelOrder methods.
type TradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trade         *Trade                 `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	mi := &file_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{22}
}

func (x *TradeResponse) GetTrade() *Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

// Response message for ListTrades method.
type ListTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesResponse) Reset() {
	*x = ListTradesResponse{}
	mi := &file_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesResponse) ProtoMessage() {}

func (x *ListTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesResponse.ProtoReflect.Descriptor instead.
func (*ListTradesResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{23}
}

func (x *ListTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Request message for GetTicks method.
type GetTicksRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContractCode         string                 `protobuf:"bytes,1,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	ContractSecurityType string                 `protobuf:"bytes,2,opt,name=contract_security_type,json=contractSecurityType,proto3" json:"contract_security_type,omitempty"`
	Date                 string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetTicksRequest) Reset() {
	*x = GetTicksRequest{}
	mi := &file_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicksRequest) ProtoMessage() {}

func (x *GetTicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicksRequest.ProtoReflect.Descriptor instead.
func (*GetTicksRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{24}
}

func (x *GetTicksRequest) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *GetTicksRequest) GetContractSecurityType() string {
	if x != nil {
		return x.ContractSecurityType
	}
	return ""
}

func (x *GetTicksRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Response message for GetTicks method.
type GetTicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticks         []*Tick                `protobuf:"bytes,1,rep,name=ticks,proto3" json:"ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicksResponse) Reset() {
	*x = GetTicksResponse{}
	mi := &file_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicksResponse) ProtoMessage() {}

func (x *GetTicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicksResponse.ProtoReflect.Descriptor instead.
func (*GetTicksResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{25}
}

func (x *GetTicksResponse) GetTicks() []*Tick {
	if x != nil {
		return x.Ticks
	}
	return nil
}

// Request message for GetKbars method.
type GetKbarsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContractCode         string                 `protobuf:"bytes,1,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	ContractSecurityType string                 `protobuf:"bytes,2,opt,name=contract_security_type,json=contractSecurityType,proto3" json:"contract_security_type,omitempty"`
	StartDate            string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetKbarsRequest) Reset() {
	*x = GetKbarsRequest{}
	mi := &file_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKbarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKbarsRequest) ProtoMessage() {}

func (x *GetKbarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKbarsRequest.ProtoReflect.Descriptor instead.
func (*GetKbarsRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{26}
}

func (x *GetKbarsRequest) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *GetKbarsRequest) GetContractSecurityType() string {
	if x != nil {
		return x.ContractSecurityType
	}
	return ""
}

func (x *GetKbarsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetKbarsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Response message for GetKbars method.
type GetKbarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kbars         []*Kbar                `protobuf:"bytes,1,rep,name=kbars,proto3" json:"kbars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKbarsResponse) Reset() {
	*x = GetKbarsResponse{}
	mi := &file_provider_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKbarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKbarsResponse) ProtoMessage() {}

func (x *GetKbarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKbarsResponse.ProtoReflect.Descriptor instead.
func (*GetKbarsResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{27}
}

func (x *GetKbarsResponse) GetKbars() []*Kbar {
	if x != nil {
		return x.Kbars
	}
	return nil
}

// Request message for GetSnapshots method.
type GetSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractCodes []string               `protobuf:"bytes,1,rep,name=contract_codes,json=contractCodes,proto3" json:"contract_codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotsRequest) Reset() {
	*x = GetSnapshotsRequest{}
	mi := &file_provider_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotsRequest) ProtoMessage() {}

func (x *GetSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{28}
}

func (x *GetSnapshotsRequest) GetContractCodes() []string {
	if x != nil {
		return x.ContractCodes
	}
	return nil
}

// Response message for GetSnapshots method.
type GetSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*Snapshot            `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotsResponse) Reset() {
	*x = GetSnapshotsResponse{}
	mi := &file_provider_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotsResponse) ProtoMessage() {}

func (x *GetSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{29}
}

func (x *GetSnapshotsResponse) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// Request message for SubscribeQuote method.
type SubscribeQuoteRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContractCode         string                 `protobuf:"bytes,1,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	ContractSecurityType string                 `protobuf:"bytes,2,opt,name=contract_security_type,json=contractSecurityType,proto3" json:"contract_security_type,omitempty"`
	QuoteType            string                 `protobuf:"bytes,3,opt,name=quote_type,json=quoteType,proto3" json:"quote_type,omitempty"` // "tick", "bidask"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubscribeQuoteRequest) Reset() {
	*x = SubscribeQuoteRequest{}
	mi := &file_provider_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeQuoteRequest) ProtoMessage() {}

func (x *SubscribeQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeQuoteRequest.ProtoReflect.Descriptor instead.
func (*SubscribeQuoteRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{30}
}

func (x *SubscribeQuoteRequest) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *SubscribeQuoteRequest) GetContractSecurityType() string {
	if x != nil {
		return x.ContractSecurityType
	}
	return ""
}

func (x *SubscribeQuoteRequest) GetQuoteType() string {
	if x != nil {
		return x.QuoteType
	}
	return ""
}

// Request message for UnsubscribeQuote method.
type UnsubscribeQuoteRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ContractCode         string                 `protobuf:"bytes,1,opt,name=contract_code,json=contractCode,proto3" json:"contract_code,omitempty"`
	ContractSecurityType string                 `protobuf:"bytes,2,opt,name=contract_security_type,json=contractSecurityType,proto3" json:"contract_security_type,omitempty"`
	QuoteType            string                 `protobuf:"bytes,3,opt,name=quote_type,json=quoteType,proto3" json:"quote_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UnsubscribeQuoteRequest) Reset() {
	*x = UnsubscribeQuoteRequest{}
	mi := &file_provider_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeQuoteRequest) ProtoMessage() {}

func (x *UnsubscribeQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeQuoteRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeQuoteRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{31}
}

func (x *UnsubscribeQuoteRequest) GetContractCode() string {
	if x != nil {
		return x.ContractCode
	}
	return ""
}

func (x *UnsubscribeQuoteRequest) GetContractSecurityType() string {
	if x != nil {
		return x.ContractSecurityType
	}
	return ""
}

func (x *UnsubscribeQuoteRequest) GetQuoteType() string {
	if x != nil {
		return x.QuoteType
	}
	return ""
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\x12\x02v1\"\xb9\x01\n" +
	"\aAccount\x12!\n" +
	"\faccount_type\x18\x01 \x01(\tR\vaccountType\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12\x1b\n" +
	"\tbroker_id\x18\x03 \x01(\tR\bbrokerId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x16\n" +
	"\x06signed\x18\x05 \x01(\bR\x06signed\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\"\xbd\x02\n" +
	"\bContract\x12#\n" +
	"\rsecurity_type\x18\x01 \x01(\tR\fsecurityType\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x19\n" +
	"\blimit_up\x18\a \x01(\x01R\alimitUp\x12\x1d\n" +
	"\n" +
	"limit_down\x18\b \x01(\x01R\tlimitDown\x12\x1c\n" +
	"\treference\x18\t \x01(\x01R\treference\x12\x1f\n" +
	"\vupdate_date\x18\n" +
	" \x01(\tR\n" +
	"updateDate\x12\x1b\n" +
	"\tday_trade\x18\v \x01(\tR\bdayTrade\"\xd1\x02\n" +
	"\x05Order\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x1d\n" +
	"\n" +
	"price_type\x18\x04 \x01(\tR\tpriceType\x12\x1d\n" +
	"\n" +
	"order_type\x18\x05 \x01(\tR\torderType\x12\x1b\n" +
	"\torder_lot\x18\x06 \x01(\tR\borderLot\x12\x1d\n" +
	"\n" +
	"order_cond\x18\a \x01(\tR\torderCond\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\x12\x14\n" +
	"\x05seqno\x18\t \x01(\tR\x05seqno\x12\x14\n" +
	"\x05ordno\x18\n" +
	" \x01(\tR\x05ordno\x12%\n" +
	"\aaccount\x18\v \x01(\v2\v.v1.AccountR\aaccount\x12!\n" +
	"\fcustom_field\x18\f \x01(\tR\vcustomField\"\xe8\x02\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\tR\n" +
	"statusCode\x12\x19\n" +
	"\border_ts\x18\x04 \x01(\x03R\aorderTs\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msg\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\x12'\n" +
	"\x0ffilled_quantity\x18\b \x01(\x03R\x0efilledQuantity\x12-\n" +
	"\x12cancelled_quantity\x18\t \x01(\x03R\x11cancelledQuantity\x12\x14\n" +
	"\x05ordno\x18\n" +
	" \x01(\tR\x05ordno\x12(\n" +
	"\bcontract\x18\v \x01(\v2\f.v1.ContractR\bcontract\x12\x1f\n" +
	"\x05order\x18\f \x01(\v2\t.v1.OrderR\x05order\"\xfd\x03\n" +
	"\x04Tick\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bdatetime\x18\x02 \x01(\tR\bdatetime\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x1b\n" +
	"\tavg_price\x18\x04 \x01(\x01R\bavgPrice\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x12\n" +
	"\x04high\x18\x06 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\x01R\x03low\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12!\n" +
	"\ftotal_amount\x18\t \x01(\x01R\vtotalAmount\x12\x16\n" +
	"\x06volume\x18\n" +
	" \x01(\x03R\x06volume\x12!\n" +
	"\ftotal_volume\x18\v \x01(\x03R\vtotalVolume\x12\x1b\n" +
	"\ttick_type\x18\f \x01(\x05R\btickType\x12\x19\n" +
	"\bchg_type\x18\r \x01(\x05R\achgType\x12\x1b\n" +
	"\tprice_chg\x18\x0e \x01(\x01R\bpriceChg\x12\x17\n" +
	"\apct_chg\x18\x0f \x01(\x01R\x06pctChg\x12+\n" +
	"\x12bid_side_total_vol\x18\x10 \x01(\x03R\x0fbidSideTotalVol\x12+\n" +
	"\x12ask_side_total_vol\x18\x11 \x01(\x03R\x0faskSideTotalVol\x12\x1a\n" +
	"\bsimtrade\x18\x12 \x01(\bR\bsimtrade\"\x96\x01\n" +
	"\x04Kbar\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x03R\x06volume\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\"\x86\x04\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12#\n" +
	"\raverage_price\x18\b \x01(\x01R\faveragePrice\x12\x16\n" +
	"\x06volume\x18\t \x01(\x03R\x06volume\x12!\n" +
	"\ftotal_volume\x18\n" +
	" \x01(\x03R\vtotalVolume\x12\x16\n" +
	"\x06amount\x18\v \x01(\x01R\x06amount\x12!\n" +
	"\ftotal_amount\x18\f \x01(\x01R\vtotalAmount\x12!\n" +
	"\fprice_change\x18\r \x01(\x01R\vpriceChange\x120\n" +
	"\x14price_change_percent\x18\x0e \x01(\x01R\x12priceChangePercent\x12\x1b\n" +
	"\tbuy_price\x18\x0f \x01(\x01R\bbuyPrice\x12\x1d\n" +
	"\n" +
	"buy_volume\x18\x10 \x01(\x03R\tbuyVolume\x12\x1d\n" +
	"\n" +
	"sell_price\x18\x11 \x01(\x01R\tsellPrice\x12\x1f\n" +
	"\vsell_volume\x18\x12 \x01(\x03R\n" +
	"sellVolume\"\xe1\x01\n" +
	"\n" +
	"ProfitLoss\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05seqno\x18\x03 \x01(\tR\x05seqno\x12\x12\n" +
	"\x04dseq\x18\x04 \x01(\tR\x04dseq\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x10\n" +
	"\x03pnl\x18\a \x01(\x01R\x03pnl\x12\x19\n" +
	"\bpr_ratio\x18\b \x01(\x01R\aprRatio\x12\x12\n" +
	"\x04cond\x18\t \x01(\tR\x04cond\x12\x12\n" +
	"\x04date\x18\n" +
	" \x01(\tR\x04date\"O\n" +
	"\n" +
	"Settlement\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x15\n" +
	"\x06t_time\x18\x03 \x01(\tR\x05tTime\"\x81\x02\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"last_price\x18\x06 \x01(\x01R\tlastPrice\x12\x10\n" +
	"\x03pnl\x18\a \x01(\x01R\x03pnl\x12\x12\n" +
	"\x04cond\x18\b \x01(\tR\x04cond\x12\x1d\n" +
	"\n" +
	"order_type\x18\t \x01(\tR\torderType\x12\x1d\n" +
	"\n" +
	"price_type\x18\n" +
	" \x01(\tR\tpriceType\"\a\n" +
	"\x05Empty\"{\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x16\n" +
	"\x06passwd\x18\x02 \x01(\tR\x06passwd\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tR\tsecretKey\"C\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x14ListAccountsResponse\x12'\n" +
	"\baccounts\x18\x01 \x03(\v2\v.v1.AccountR\baccounts\"N\n" +
	"\x16AccountBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"K\n" +
	"\x17ListSettlementsResponse\x120\n" +
	"\vsettlements\x18\x01 \x03(\v2\x0e.v1.SettlementR\vsettlements\"Q\n" +
	"\x15ListProfitLossRequest\x12\x1d\n" +
	"\n" +
	"begin_date\x18\x01 \x01(\tR\tbeginDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"I\n" +
	"\x16ListProfitLossResponse\x12/\n" +
	"\vprofit_loss\x18\x01 \x03(\v2\x0e.v1.ProfitLossR\n" +
	"profitLoss\"C\n" +
	"\x15ListPositionsResponse\x12*\n" +
	"\tpositions\x18\x01 \x03(\v2\f.v1.PositionR\tpositions\"\xb2\x02\n" +
	"\x11PlaceOrderRequest\x12#\n" +
	"\rcontract_code\x18\x01 \x01(\tR\fcontractCode\x124\n" +
	"\x16contract_security_type\x18\x02 \x01(\tR\x14contractSecurityType\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x1d\n" +
	"\n" +
	"price_type\x18\x06 \x01(\tR\tpriceType\x12\x1d\n" +
	"\n" +
	"order_type\x18\a \x01(\tR\torderType\x12\x1b\n" +
	"\torder_lot\x18\b \x01(\tR\borderLot\x12\x1d\n" +
	"\n" +
	"account_id\x18\t \x01(\tR\taccountId\"a\n" +
	"\x12UpdateOrderRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\"0\n" +
	"\rTradeResponse\x12\x1f\n" +
	"\x05trade\x18\x01 \x01(\v2\t.v1.TradeR\x05trade\"7\n" +
	"\x12ListTradesResponse\x12!\n" +
	"\x06trades\x18\x01 \x03(\v2\t.v1.TradeR\x06trades\"\x80\x01\n" +
	"\x0fGetTicksRequest\x12#\n" +
	"\rcontract_code\x18\x01 \x01(\tR\fcontractCode\x124\n" +
	"\x16contract_security_type\x18\x02 \x01(\tR\x14contractSecurityType\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"2\n" +
	"\x10GetTicksResponse\x12\x1e\n" +
	"\x05ticks\x18\x01 \x03(\v2\b.v1.TickR\x05ticks\"\xa6\x01\n" +
	"\x0fGetKbarsRequest\x12#\n" +
	"\rcontract_code\x18\x01 \x01(\tR\fcontractCode\x124\n" +
	"\x16contract_security_type\x18\x02 \x01(\tR\x14contractSecurityType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"2\n" +
	"\x10GetKbarsResponse\x12\x1e\n" +
	"\x05kbars\x18\x01 \x03(\v2\b.v1.KbarR\x05kbars\"<\n" +
	"\x13GetSnapshotsRequest\x12%\n" +
	"\x0econtract_codes\x18\x01 \x03(\tR\rcontractCodes\"B\n" +
	"\x14GetSnapshotsResponse\x12*\n" +
	"\tsnapshots\x18\x01 \x03(\v2\f.v1.SnapshotR\tsnapshots\"\x91\x01\n" +
	"\x15SubscribeQuoteRequest\x12#\n" +
	"\rcontract_code\x18\x01 \x01(\tR\fcontractCode\x124\n" +
	"\x16contract_security_type\x18\x02 \x01(\tR\x14contractSecurityType\x12\x1d\n" +
	"\n" +
	"quote_type\x18\x03 \x01(\tR\tquoteType\"\x93\x01\n" +
	"\x17UnsubscribeQuoteRequest\x12#\n" +
	"\rcontract_code\x18\x01 \x01(\tR\fcontractCode\x124\n" +
	"\x16contract_security_type\x18\x02 \x01(\tR\x14contractSecurityType\x12\x1d\n" +
	"\n" +
	"quote_type\x18\x03 \x01(\tR\tquoteType2\xb3\a\n" +
	"\x0fShioajiProvider\x12.\n" +
	"\x05Login\x12\x10.v1.LoginRequest\x1a\x11.v1.LoginResponse\"\x00\x125\n" +
	"\fListAccounts\x12\t.v1.Empty\x1a\x18.v1.ListAccountsResponse\"\x00\x12<\n" +
	"\x11GetAccountBalance\x12\t.v1.Empty\x1a\x1a.v1.AccountBalanceResponse\"\x00\x12;\n" +
	"\x0fListSettlements\x12\t.v1.Empty\x1a\x1b.v1.ListSettlementsResponse\"\x00\x12I\n" +
	"\x0eListProfitLoss\x12\x19.v1.ListProfitLossRequest\x1a\x1a.v1.ListProfitLossResponse\"\x00\x127\n" +
	"\rListPositions\x12\t.v1.Empty\x1a\x19.v1.ListPositionsResponse\"\x00\x128\n" +
	"\n" +
	"PlaceOrder\x12\x15.v1.PlaceOrderRequest\x1a\x11.v1.TradeResponse\"\x00\x12:\n" +
	"\vUpdateOrder\x12\x16.v1.UpdateOrderRequest\x1a\x11.v1.TradeResponse\"\x00\x12:\n" +
	"\vCancelOrder\x12\x16.v1.CancelOrderRequest\x1a\x11.v1.TradeResponse\"\x00\x121\n" +
	"\n" +
	"ListTrades\x12\t.v1.Empty\x1a\x16.v1.ListTradesResponse\"\x00\x12&\n" +
	"\fUpdateStatus\x12\t.v1.Empty\x1a\t.v1.Empty\"\x00\x127\n" +
	"\bGetTicks\x12\x13.v1.GetTicksRequest\x1a\x14.v1.GetTicksResponse\"\x00\x127\n" +
	"\bGetKbars\x12\x13.v1.GetKbarsRequest\x1a\x14.v1.GetKbarsResponse\"\x00\x12C\n" +
	"\fGetSnapshots\x12\x17.v1.GetSnapshotsRequest\x1a\x18.v1.GetSnapshotsResponse\"\x00\x128\n" +
	"\x0eSubscribeQuote\x12\x19.v1.SubscribeQuoteRequest\x1a\t.v1.Empty\"\x00\x12<\n" +
	"\x10UnsubscribeQuote\x12\x1b.v1.UnsubscribeQuoteRequest\x1a\t.v1.Empty\"\x00B\x1aZ\x18phoenix/processor/pkg/pbb\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_provider_proto_goTypes = []any{
	(*Account)(nil),                 // 0: v1.Account
	(*Contract)(nil),                // 1: v1.Contract
	(*Order)(nil),                   // 2: v1.Order
	(*Trade)(nil),                   // 3: v1.Trade
	(*Tick)(nil),                    // 4: v1.Tick
	(*Kbar)(nil),                    // 5: v1.Kbar
	(*Snapshot)(nil),                // 6: v1.Snapshot
	(*ProfitLoss)(nil),              // 7: v1.ProfitLoss
	(*Settlement)(nil),              // 8: v1.Settlement
	(*Position)(nil),                // 9: v1.Position
	(*Empty)(nil),                   // 10: v1.Empty
	(*LoginRequest)(nil),            // 11: v1.LoginRequest
	(*LoginResponse)(nil),           // 12: v1.LoginResponse
	(*ListAccountsResponse)(nil),    // 13: v1.ListAccountsResponse
	(*AccountBalanceResponse)(nil),  // 14: v1.AccountBalanceResponse
	(*ListSettlementsResponse)(nil), // 15: v1.ListSettlementsResponse
	(*ListProfitLossRequest)(nil),   // 16: v1.ListProfitLossRequest
	(*ListProfitLossResponse)(nil),  // 17: v1.ListProfitLossResponse
	(*ListPositionsResponse)(nil),   // 18: v1.ListPositionsResponse
	(*PlaceOrderRequest)(nil),       // 19: v1.PlaceOrderRequest
	(*UpdateOrderRequest)(nil),      // 20: v1.UpdateOrderRequest
	(*CancelOrderRequest)(nil),      // 21: v1.CancelOrderRequest
	(*TradeResponse)(nil),           // 22: v1.TradeResponse
	(*ListTradesResponse)(nil),      // 23: v1.ListTradesResponse
	(*GetTicksRequest)(nil),         // 24: v1.GetTicksRequest
	(*GetTicksResponse)(nil),        // 25: v1.GetTicksResponse
	(*GetKbarsRequest)(nil),         // 26: v1.GetKbarsRequest
	(*GetKbarsResponse)(nil),        // 27: v1.GetKbarsResponse
	(*GetSnapshotsRequest)(nil),     // 28: v1.GetSnapshotsRequest
	(*GetSnapshotsResponse)(nil),    // 29: v1.GetSnapshotsResponse
	(*SubscribeQuoteRequest)(nil),   // 30: v1.SubscribeQuoteRequest
	(*UnsubscribeQuoteRequest)(nil), // 31: v1.UnsubscribeQuoteRequest
}
var file_provider_proto_depIdxs = []int32{
	0,  // 0: v1.Order.account:type_name -> v1.Account
	1,  // 1: v1.Trade.contract:type_name -> v1.Contract
	2,  // 2: v1.Trade.order:type_name -> v1.Order
	0,  // 3: v1.ListAccountsResponse.accounts:type_name -> v1.Account
	8,  // 4: v1.ListSettlementsResponse.settlements:type_name -> v1.Settlement
	7,  // 5: v1.ListProfitLossResponse.profit_loss:type_name -> v1.ProfitLoss
	9,  // 6: v1.ListPositionsResponse.positions:type_name -> v1.Position
	3,  // 7: v1.TradeResponse.trade:type_name -> v1.Trade
	3,  // 8: v1.ListTradesResponse.trades:type_name -> v1.Trade
	4,  // 9: v1.GetTicksResponse.ticks:type_name -> v1.Tick
	5,  // 10: v1.GetKbarsResponse.kbars:type_name -> v1.Kbar
	6,  // 11: v1.GetSnapshotsResponse.snapshots:type_name -> v1.Snapshot
	11, // 12: v1.ShioajiProvider.Login:input_type -> v1.LoginRequest
	10, // 13: v1.ShioajiProvider.ListAccounts:input_type -> v1.Empty
	10, // 14: v1.ShioajiProvider.GetAccountBalance:input_type -> v1.Empty
	10, // 15: v1.ShioajiProvider.ListSettlements:input_type -> v1.Empty
	16, // 16: v1.ShioajiProvider.ListProfitLoss:input_type -> v1.ListProfitLossRequest
	10, // 17: v1.ShioajiProvider.ListPositions:input_type -> v1.Empty
	19, // 18: v1.ShioajiProvider.PlaceOrder:input_type -> v1.PlaceOrderRequest
	20, // 19: v1.ShioajiProvider.UpdateOrder:input_type -> v1.UpdateOrderRequest
	21, // 20: v1.ShioajiProvider.CancelOrder:input_type -> v1.CancelOrderRequest
	10, // 21: v1.ShioajiProvider.ListTrades:input_type -> v1.Empty
	10, // 22: v1.ShioajiProvider.UpdateStatus:input_type -> v1.Empty
	24, // 23: v1.ShioajiProvider.GetTicks:input_type -> v1.GetTicksRequest
	26, // 24: v1.ShioajiProvider.GetKbars:input_type -> v1.GetKbarsRequest
	28, // 25: v1.ShioajiProvider.GetSnapshots:input_type -> v1.GetSnapshotsRequest
	30, // 26: v1.ShioajiProvider.SubscribeQuote:input_type -> v1.SubscribeQuoteRequest
	31, // 27: v1.ShioajiProvider.UnsubscribeQuote:input_type -> v1.UnsubscribeQuoteRequest
	12, // 28: v1.ShioajiProvider.Login:output_type -> v1.LoginResponse
	13, // 29: v1.ShioajiProvider.ListAccounts:output_type -> v1.ListAccountsResponse
	14, // 30: v1.ShioajiProvider.GetAccountBalance:output_type -> v1.AccountBalanceResponse
	15, // 31: v1.ShioajiProvider.ListSettlements:output_type -> v1.ListSettlementsResponse
	17, // 32: v1.ShioajiProvider.ListProfitLoss:output_type -> v1.ListProfitLossResponse
	18, // 33: v1.ShioajiProvider.ListPositions:output_type -> v1.ListPositionsResponse
	22, // 34: v1.ShioajiProvider.PlaceOrder:output_type -> v1.TradeResponse
	22, // 35: v1.ShioajiProvider.UpdateOrder:output_type -> v1.TradeResponse
	22, // 36: v1.ShioajiProvider.CancelOrder:output_type -> v1.TradeResponse
	23, // 37: v1.ShioajiProvider.ListTrades:output_type -> v1.ListTradesResponse
	10, // 38: v1.ShioajiProvider.UpdateStatus:output_type -> v1.Empty
	25, // 39: v1.ShioajiProvider.GetTicks:output_type -> v1.GetTicksResponse
	27, // 40: v1.ShioajiProvider.GetKbars:output_type -> v1.GetKbarsResponse
	29, // 41: v1.ShioajiProvider.GetSnapshots:output_type -> v1.GetSnapshotsResponse
	10, // 42: v1.ShioajiProvider.SubscribeQuote:output_type -> v1.Empty
	10, // 43: v1.ShioajiProvider.UnsubscribeQuote:output_type -> v1.Empty
	28, // [28:44] is the sub-list for method output_type
	12, // [12:28] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
