// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: provider.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShioajiProvider_Login_FullMethodName             = "/v1.ShioajiProvider/Login"
	ShioajiProvider_ListAccounts_FullMethodName      = "/v1.ShioajiProvider/ListAccounts"
	ShioajiProvider_GetAccountBalance_FullMethodName = "/v1.ShioajiProvider/GetAccountBalance"
	ShioajiProvider_ListSettlements_FullMethodName   = "/v1.ShioajiProvider/ListSettlements"
	ShioajiProvider_ListProfitLoss_FullMethodName    = "/v1.ShioajiProvider/ListProfitLoss"
	ShioajiProvider_ListPositions_FullMethodName     = "/v1.ShioajiProvider/ListPositions"
	ShioajiProvider_PlaceOrder_FullMethodName        = "/v1.ShioajiProvider/PlaceOrder"
	ShioajiProvider_UpdateOrder_FullMethodName       = "/v1.ShioajiProvider/UpdateOrder"
	ShioajiProvider_CancelOrder_FullMethodName       = "/v1.ShioajiProvider/CancelOrder"
	ShioajiProvider_ListTrades_FullMethodName        = "/v1.ShioajiProvider/ListTrades"
	ShioajiProvider_UpdateStatus_FullMethodName      = "/v1.ShioajiProvider/UpdateStatus"
	ShioajiProvider_GetTicks_FullMethodName          = "/v1.ShioajiProvider/GetTicks"
	ShioajiProvider_GetKbars_FullMethodName          = "/v1.ShioajiProvider/GetKbars"
	ShioajiProvider_GetSnapshots_FullMethodName      = "/v1.ShioajiProvider/GetSnapshots"
	ShioajiProvider_SubscribeQuote_FullMethodName    = "/v1.ShioajiProvider/SubscribeQuote"
	ShioajiProvider_UnsubscribeQuote_FullMethodName  = "/v1.ShioajiProvider/UnsubscribeQuote"
)

// ShioajiProviderClient is the client API for ShioajiProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service Definition
// ShioajiProvider service provides an interface for trading and market data access.
type ShioajiProviderClient interface {
	// Authenticates the user and establishes a connection with the Shioaji API.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Retrieves all available trading accounts for the logged-in user.
	ListAccounts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	// Queries the current balance for the default stock account.
	GetAccountBalance(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AccountBalanceResponse, error)
	// Retrieves stock account settlement details.
	ListSettlements(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSettlementsResponse, error)
	// Queries realized profit and loss for a specified date range.
	ListProfitLoss(ctx context.Context, in *ListProfitLossRequest, opts ...grpc.CallOption) (*ListProfitLossResponse, error)
	// Retrieves current unrealized positions and their profit/loss.
	ListPositions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListPositionsResponse, error)
	// Submits a new trading order for a specific contract.
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*TradeResponse, error)
	// Modifies the price or quantity of an existing active order.
	UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*TradeResponse, error)
	// Requests the cancellation of an existing active order.
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*TradeResponse, error)
	// Lists all active trades and their statuses.
	ListTrades(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTradesResponse, error)
	// Forces an update of order and trade statuses for the current session.
	UpdateStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Retrieves historical tick data for a contract.
	GetTicks(ctx context.Context, in *GetTicksRequest, opts ...grpc.CallOption) (*GetTicksResponse, error)
	// Retrieves historical candlestick (K-bar) data for a contract.
	GetKbars(ctx context.Context, in *GetKbarsRequest, opts ...grpc.CallOption) (*GetKbarsResponse, error)
	// Retrieves current market snapshots for one or more contracts.
	GetSnapshots(ctx context.Context, in *GetSnapshotsRequest, opts ...grpc.CallOption) (*GetSnapshotsResponse, error)
	// Subscribes to real-time market data (ticks or quotes) for a contract.
	SubscribeQuote(ctx context.Context, in *SubscribeQuoteRequest, opts ...grpc.CallOption) (*Empty, error)
	// Unsubscribes from real-time market data updates for a contract.
	UnsubscribeQuote(ctx context.Context, in *UnsubscribeQuoteRequest, opts ...grpc.CallOption) (*Empty, error)
}

type shioajiProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewShioajiProviderClient(cc grpc.ClientConnInterface) ShioajiProviderClient {
	return &shioajiProviderClient{cc}
}

func (c *shioajiProviderClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) ListAccounts(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_ListAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) GetAccountBalance(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AccountBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountBalanceResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_GetAccountBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) ListSettlements(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSettlementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSettlementsResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_ListSettlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) ListProfitLoss(ctx context.Context, in *ListProfitLossRequest, opts ...grpc.CallOption) (*ListProfitLossResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfitLossResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_ListProfitLoss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) ListPositions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPositionsResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_ListPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*TradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) UpdateOrder(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*TradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_UpdateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*TradeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) ListTrades(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTradesResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_ListTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) UpdateStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShioajiProvider_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) GetTicks(ctx context.Context, in *GetTicksRequest, opts ...grpc.CallOption) (*GetTicksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicksResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_GetTicks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) GetKbars(ctx context.Context, in *GetKbarsRequest, opts ...grpc.CallOption) (*GetKbarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKbarsResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_GetKbars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) GetSnapshots(ctx context.Context, in *GetSnapshotsRequest, opts ...grpc.CallOption) (*GetSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotsResponse)
	err := c.cc.Invoke(ctx, ShioajiProvider_GetSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) SubscribeQuote(ctx context.Context, in *SubscribeQuoteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShioajiProvider_SubscribeQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shioajiProviderClient) UnsubscribeQuote(ctx context.Context, in *UnsubscribeQuoteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShioajiProvider_UnsubscribeQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShioajiProviderServer is the server API for ShioajiProvider service.
// All implementations must embed UnimplementedShioajiProviderServer
// for forward compatibility.
//
// Service Definition
// ShioajiProvider service provides an interface for trading and market data access.
type ShioajiProviderServer interface {
	// Authenticates the user and establishes a connection with the Shioaji API.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Retrieves all available trading accounts for the logged-in user.
	ListAccounts(context.Context, *Empty) (*ListAccountsResponse, error)
	// Queries the current balance for the default stock account.
	GetAccountBalance(context.Context, *Empty) (*AccountBalanceResponse, error)
	// Retrieves stock account settlement details.
	ListSettlements(context.Context, *Empty) (*ListSettlementsResponse, error)
	// Queries realized profit and loss for a specified date range.
	ListProfitLoss(context.Context, *ListProfitLossRequest) (*ListProfitLossResponse, error)
	// Retrieves current unrealized positions and their profit/loss.
	ListPositions(context.Context, *Empty) (*ListPositionsResponse, error)
	// Submits a new trading order for a specific contract.
	PlaceOrder(context.Context, *PlaceOrderRequest) (*TradeResponse, error)
	// Modifies the price or quantity of an existing active order.
	UpdateOrder(context.Context, *UpdateOrderRequest) (*TradeResponse, error)
	// Requests the cancellation of an existing active order.
	CancelOrder(context.Context, *CancelOrderRequest) (*TradeResponse, error)
	// Lists all active trades and their statuses.
	ListTrades(context.Context, *Empty) (*ListTradesResponse, error)
	// Forces an update of order and trade statuses for the current session.
	UpdateStatus(context.Context, *Empty) (*Empty, error)
	// Retrieves historical tick data for a contract.
	GetTicks(context.Context, *GetTicksRequest) (*GetTicksResponse, error)
	// Retrieves historical candlestick (K-bar) data for a contract.
	GetKbars(context.Context, *GetKbarsRequest) (*GetKbarsResponse, error)
	// Retrieves current market snapshots for one or more contracts.
	GetSnapshots(context.Context, *GetSnapshotsRequest) (*GetSnapshotsResponse, error)
	// Subscribes to real-time market data (ticks or quotes) for a contract.
	SubscribeQuote(context.Context, *SubscribeQuoteRequest) (*Empty, error)
	// Unsubscribes from real-time market data updates for a contract.
	UnsubscribeQuote(context.Context, *UnsubscribeQuoteRequest) (*Empty, error)
	mustEmbedUnimplementedShioajiProviderServer()
}

// UnimplementedShioajiProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShioajiProviderServer struct{}

func (UnimplementedShioajiProviderServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedShioajiProviderServer) ListAccounts(context.Context, *Empty) (*ListAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedShioajiProviderServer) GetAccountBalance(context.Context, *Empty) (*AccountBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountBalance not implemented")
}
func (UnimplementedShioajiProviderServer) ListSettlements(context.Context, *Empty) (*ListSettlementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSettlements not implemented")
}
func (UnimplementedShioajiProviderServer) ListProfitLoss(context.Context, *ListProfitLossRequest) (*ListProfitLossResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProfitLoss not implemented")
}
func (UnimplementedShioajiProviderServer) ListPositions(context.Context, *Empty) (*ListPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPositions not implemented")
}
func (UnimplementedShioajiProviderServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*TradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedShioajiProviderServer) UpdateOrder(context.Context, *UpdateOrderRequest) (*TradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedShioajiProviderServer) CancelOrder(context.Context, *CancelOrderRequest) (*TradeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedShioajiProviderServer) ListTrades(context.Context, *Empty) (*ListTradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrades not implemented")
}
func (UnimplementedShioajiProviderServer) UpdateStatus(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedShioajiProviderServer) GetTicks(context.Context, *GetTicksRequest) (*GetTicksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicks not implemented")
}
func (UnimplementedShioajiProviderServer) GetKbars(context.Context, *GetKbarsRequest) (*GetKbarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKbars not implemented")
}
func (UnimplementedShioajiProviderServer) GetSnapshots(context.Context, *GetSnapshotsRequest) (*GetSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshots not implemented")
}
func (UnimplementedShioajiProviderServer) SubscribeQuote(context.Context, *SubscribeQuoteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeQuote not implemented")
}
func (UnimplementedShioajiProviderServer) UnsubscribeQuote(context.Context, *UnsubscribeQuoteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeQuote not implemented")
}
func (UnimplementedShioajiProviderServer) mustEmbedUnimplementedShioajiProviderServer() {}
func (UnimplementedShioajiProviderServer) testEmbeddedByValue()                         {}

// UnsafeShioajiProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShioajiProviderServer will
// result in compilation errors.
type UnsafeShioajiProviderServer interface {
	mustEmbedUnimplementedShioajiProviderServer()
}

func RegisterShioajiProviderServer(s grpc.ServiceRegistrar, srv ShioajiProviderServer) {
	// If the following call panics, it indicates UnimplementedShioajiProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShioajiProvider_ServiceDesc, srv)
}

func _ShioajiProvider_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_ListAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).ListAccounts(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_GetAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).GetAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_GetAccountBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).GetAccountBalance(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_ListSettlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).ListSettlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_ListSettlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).ListSettlements(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_ListProfitLoss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfitLossRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).ListProfitLoss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_ListProfitLoss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).ListProfitLoss(ctx, req.(*ListProfitLossRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_ListPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).ListPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_ListPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).ListPositions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_UpdateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).UpdateOrder(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_ListTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).ListTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_ListTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).ListTrades(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).UpdateStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_GetTicks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).GetTicks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_GetTicks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).GetTicks(ctx, req.(*GetTicksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_GetKbars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKbarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).GetKbars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_GetKbars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).GetKbars(ctx, req.(*GetKbarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_GetSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).GetSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_GetSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).GetSnapshots(ctx, req.(*GetSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_SubscribeQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).SubscribeQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_SubscribeQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).SubscribeQuote(ctx, req.(*SubscribeQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShioajiProvider_UnsubscribeQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShioajiProviderServer).UnsubscribeQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShioajiProvider_UnsubscribeQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShioajiProviderServer).UnsubscribeQuote(ctx, req.(*UnsubscribeQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShioajiProvider_ServiceDesc is the grpc.ServiceDesc for ShioajiProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShioajiProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ShioajiProvider",
	HandlerType: (*ShioajiProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _ShioajiProvider_Login_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _ShioajiProvider_ListAccounts_Handler,
		},
		{
			MethodName: "GetAccountBalance",
			Handler:    _ShioajiProvider_GetAccountBalance_Handler,
		},
		{
			MethodName: "ListSettlements",
			Handler:    _ShioajiProvider_ListSettlements_Handler,
		},
		{
			MethodName: "ListProfitLoss",
			Handler:    _ShioajiProvider_ListProfitLoss_Handler,
		},
		{
			MethodName: "ListPositions",
			Handler:    _ShioajiProvider_ListPositions_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _ShioajiProvider_PlaceOrder_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _ShioajiProvider_UpdateOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _ShioajiProvider_CancelOrder_Handler,
		},
		{
			MethodName: "ListTrades",
			Handler:    _ShioajiProvider_ListTrades_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _ShioajiProvider_UpdateStatus_Handler,
		},
		{
			MethodName: "GetTicks",
			Handler:    _ShioajiProvider_GetTicks_Handler,
		},
		{
			MethodName: "GetKbars",
			Handler:    _ShioajiProvider_GetKbars_Handler,
		},
		{
			MethodName: "GetSnapshots",
			Handler:    _ShioajiProvider_GetSnapshots_Handler,
		},
		{
			MethodName: "SubscribeQuote",
			Handler:    _ShioajiProvider_SubscribeQuote_Handler,
		},
		{
			MethodName: "UnsubscribeQuote",
			Handler:    _ShioajiProvider_UnsubscribeQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "provider.proto",
}
