// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/client/interface.go -destination=internal/client/mock_client.go -package=client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	pb "phoenix/processor/pkg/pb"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockShioajiClient is a mock of ShioajiClient interface.
type MockShioajiClient struct {
	ctrl     *gomock.Controller
	recorder *MockShioajiClientMockRecorder
	isgomock struct{}
}

// MockShioajiClientMockRecorder is the mock recorder for MockShioajiClient.
type MockShioajiClientMockRecorder struct {
	mock *MockShioajiClient
}

// NewMockShioajiClient creates a new mock instance.
func NewMockShioajiClient(ctrl *gomock.Controller) *MockShioajiClient {
	mock := &MockShioajiClient{ctrl: ctrl}
	mock.recorder = &MockShioajiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShioajiClient) EXPECT() *MockShioajiClientMockRecorder {
	return m.recorder
}

// ActivateCA mocks base method.
func (m *MockShioajiClient) ActivateCA(ctx context.Context, in *pb.ActivateCARequest, opts ...grpc.CallOption) (*pb.ActivateCAResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ActivateCA", varargs...)
	ret0, _ := ret[0].(*pb.ActivateCAResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivateCA indicates an expected call of ActivateCA.
func (mr *MockShioajiClientMockRecorder) ActivateCA(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateCA", reflect.TypeOf((*MockShioajiClient)(nil).ActivateCA), varargs...)
}

// CancelComboOrder mocks base method.
func (m *MockShioajiClient) CancelComboOrder(ctx context.Context, in *pb.CancelComboOrderRequest, opts ...grpc.CallOption) (*pb.ComboTrade, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelComboOrder", varargs...)
	ret0, _ := ret[0].(*pb.ComboTrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelComboOrder indicates an expected call of CancelComboOrder.
func (mr *MockShioajiClientMockRecorder) CancelComboOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelComboOrder", reflect.TypeOf((*MockShioajiClient)(nil).CancelComboOrder), varargs...)
}

// CancelOrder mocks base method.
func (m *MockShioajiClient) CancelOrder(ctx context.Context, in *pb.CancelOrderRequest, opts ...grpc.CallOption) (*pb.Trade, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelOrder", varargs...)
	ret0, _ := ret[0].(*pb.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockShioajiClientMockRecorder) CancelOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockShioajiClient)(nil).CancelOrder), varargs...)
}

// Close mocks base method.
func (m *MockShioajiClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockShioajiClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockShioajiClient)(nil).Close))
}

// CreditEnquires mocks base method.
func (m *MockShioajiClient) CreditEnquires(ctx context.Context, in *pb.CreditEnquiresRequest, opts ...grpc.CallOption) (*pb.CreditEnquiresResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreditEnquires", varargs...)
	ret0, _ := ret[0].(*pb.CreditEnquiresResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreditEnquires indicates an expected call of CreditEnquires.
func (mr *MockShioajiClientMockRecorder) CreditEnquires(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreditEnquires", reflect.TypeOf((*MockShioajiClient)(nil).CreditEnquires), varargs...)
}

// FetchContracts mocks base method.
func (m *MockShioajiClient) FetchContracts(ctx context.Context, in *pb.FetchContractsRequest, opts ...grpc.CallOption) (*pb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchContracts", varargs...)
	ret0, _ := ret[0].(*pb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchContracts indicates an expected call of FetchContracts.
func (mr *MockShioajiClientMockRecorder) FetchContracts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchContracts", reflect.TypeOf((*MockShioajiClient)(nil).FetchContracts), varargs...)
}

// GetAccountBalance mocks base method.
func (m *MockShioajiClient) GetAccountBalance(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.AccountBalance, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountBalance", varargs...)
	ret0, _ := ret[0].(*pb.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockShioajiClientMockRecorder) GetAccountBalance(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockShioajiClient)(nil).GetAccountBalance), varargs...)
}

// GetCAExpireTime mocks base method.
func (m *MockShioajiClient) GetCAExpireTime(ctx context.Context, in *pb.GetCAExpireTimeRequest, opts ...grpc.CallOption) (*pb.GetCAExpireTimeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCAExpireTime", varargs...)
	ret0, _ := ret[0].(*pb.GetCAExpireTimeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCAExpireTime indicates an expected call of GetCAExpireTime.
func (mr *MockShioajiClientMockRecorder) GetCAExpireTime(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCAExpireTime", reflect.TypeOf((*MockShioajiClient)(nil).GetCAExpireTime), varargs...)
}

// GetDailyQuotes mocks base method.
func (m *MockShioajiClient) GetDailyQuotes(ctx context.Context, in *pb.GetDailyQuotesRequest, opts ...grpc.CallOption) (*pb.DailyQuotes, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDailyQuotes", varargs...)
	ret0, _ := ret[0].(*pb.DailyQuotes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyQuotes indicates an expected call of GetDailyQuotes.
func (mr *MockShioajiClientMockRecorder) GetDailyQuotes(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyQuotes", reflect.TypeOf((*MockShioajiClient)(nil).GetDailyQuotes), varargs...)
}

// GetEarmarkingDetail mocks base method.
func (m *MockShioajiClient) GetEarmarkingDetail(ctx context.Context, in *pb.GetEarmarkingDetailRequest, opts ...grpc.CallOption) (*pb.EarmarkStocksDetailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEarmarkingDetail", varargs...)
	ret0, _ := ret[0].(*pb.EarmarkStocksDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEarmarkingDetail indicates an expected call of GetEarmarkingDetail.
func (mr *MockShioajiClientMockRecorder) GetEarmarkingDetail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEarmarkingDetail", reflect.TypeOf((*MockShioajiClient)(nil).GetEarmarkingDetail), varargs...)
}

// GetKbars mocks base method.
func (m *MockShioajiClient) GetKbars(ctx context.Context, in *pb.GetKbarsRequest, opts ...grpc.CallOption) (*pb.Kbars, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKbars", varargs...)
	ret0, _ := ret[0].(*pb.Kbars)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKbars indicates an expected call of GetKbars.
func (mr *MockShioajiClientMockRecorder) GetKbars(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKbars", reflect.TypeOf((*MockShioajiClient)(nil).GetKbars), varargs...)
}

// GetMargin mocks base method.
func (m *MockShioajiClient) GetMargin(ctx context.Context, in *pb.GetMarginRequest, opts ...grpc.CallOption) (*pb.Margin, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMargin", varargs...)
	ret0, _ := ret[0].(*pb.Margin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMargin indicates an expected call of GetMargin.
func (mr *MockShioajiClientMockRecorder) GetMargin(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMargin", reflect.TypeOf((*MockShioajiClient)(nil).GetMargin), varargs...)
}

// GetNotice mocks base method.
func (m *MockShioajiClient) GetNotice(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.Notice, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNotice", varargs...)
	ret0, _ := ret[0].(*pb.Notice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotice indicates an expected call of GetNotice.
func (mr *MockShioajiClientMockRecorder) GetNotice(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotice", reflect.TypeOf((*MockShioajiClient)(nil).GetNotice), varargs...)
}

// GetOrderDealRecords mocks base method.
func (m *MockShioajiClient) GetOrderDealRecords(ctx context.Context, in *pb.GetOrderDealRecordsRequest, opts ...grpc.CallOption) (*pb.GetOrderDealRecordsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderDealRecords", varargs...)
	ret0, _ := ret[0].(*pb.GetOrderDealRecordsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderDealRecords indicates an expected call of GetOrderDealRecords.
func (mr *MockShioajiClientMockRecorder) GetOrderDealRecords(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderDealRecords", reflect.TypeOf((*MockShioajiClient)(nil).GetOrderDealRecords), varargs...)
}

// GetPunish mocks base method.
func (m *MockShioajiClient) GetPunish(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.Punish, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPunish", varargs...)
	ret0, _ := ret[0].(*pb.Punish)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPunish indicates an expected call of GetPunish.
func (mr *MockShioajiClientMockRecorder) GetPunish(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPunish", reflect.TypeOf((*MockShioajiClient)(nil).GetPunish), varargs...)
}

// GetScanners mocks base method.
func (m *MockShioajiClient) GetScanners(ctx context.Context, in *pb.GetScannersRequest, opts ...grpc.CallOption) (*pb.GetScannersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetScanners", varargs...)
	ret0, _ := ret[0].(*pb.GetScannersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScanners indicates an expected call of GetScanners.
func (mr *MockShioajiClientMockRecorder) GetScanners(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanners", reflect.TypeOf((*MockShioajiClient)(nil).GetScanners), varargs...)
}

// GetSettlements mocks base method.
func (m *MockShioajiClient) GetSettlements(ctx context.Context, in *pb.GetSettlementsRequest, opts ...grpc.CallOption) (*pb.GetSettlementsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSettlements", varargs...)
	ret0, _ := ret[0].(*pb.GetSettlementsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettlements indicates an expected call of GetSettlements.
func (mr *MockShioajiClientMockRecorder) GetSettlements(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettlements", reflect.TypeOf((*MockShioajiClient)(nil).GetSettlements), varargs...)
}

// GetShortStockSources mocks base method.
func (m *MockShioajiClient) GetShortStockSources(ctx context.Context, in *pb.GetShortStockSourcesRequest, opts ...grpc.CallOption) (*pb.GetShortStockSourcesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetShortStockSources", varargs...)
	ret0, _ := ret[0].(*pb.GetShortStockSourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortStockSources indicates an expected call of GetShortStockSources.
func (mr *MockShioajiClientMockRecorder) GetShortStockSources(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortStockSources", reflect.TypeOf((*MockShioajiClient)(nil).GetShortStockSources), varargs...)
}

// GetSnapshots mocks base method.
func (m *MockShioajiClient) GetSnapshots(ctx context.Context, in *pb.GetSnapshotsRequest, opts ...grpc.CallOption) (*pb.GetSnapshotsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSnapshots", varargs...)
	ret0, _ := ret[0].(*pb.GetSnapshotsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshots indicates an expected call of GetSnapshots.
func (mr *MockShioajiClientMockRecorder) GetSnapshots(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshots", reflect.TypeOf((*MockShioajiClient)(nil).GetSnapshots), varargs...)
}

// GetStockReserveDetail mocks base method.
func (m *MockShioajiClient) GetStockReserveDetail(ctx context.Context, in *pb.GetStockReserveDetailRequest, opts ...grpc.CallOption) (*pb.ReserveStocksDetailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStockReserveDetail", varargs...)
	ret0, _ := ret[0].(*pb.ReserveStocksDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockReserveDetail indicates an expected call of GetStockReserveDetail.
func (mr *MockShioajiClientMockRecorder) GetStockReserveDetail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockReserveDetail", reflect.TypeOf((*MockShioajiClient)(nil).GetStockReserveDetail), varargs...)
}

// GetStockReserveSummary mocks base method.
func (m *MockShioajiClient) GetStockReserveSummary(ctx context.Context, in *pb.GetStockReserveSummaryRequest, opts ...grpc.CallOption) (*pb.ReserveStocksSummaryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStockReserveSummary", varargs...)
	ret0, _ := ret[0].(*pb.ReserveStocksSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockReserveSummary indicates an expected call of GetStockReserveSummary.
func (mr *MockShioajiClientMockRecorder) GetStockReserveSummary(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockReserveSummary", reflect.TypeOf((*MockShioajiClient)(nil).GetStockReserveSummary), varargs...)
}

// GetTicks mocks base method.
func (m *MockShioajiClient) GetTicks(ctx context.Context, in *pb.GetTicksRequest, opts ...grpc.CallOption) (*pb.Ticks, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTicks", varargs...)
	ret0, _ := ret[0].(*pb.Ticks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTicks indicates an expected call of GetTicks.
func (mr *MockShioajiClientMockRecorder) GetTicks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTicks", reflect.TypeOf((*MockShioajiClient)(nil).GetTicks), varargs...)
}

// GetTradingLimits mocks base method.
func (m *MockShioajiClient) GetTradingLimits(ctx context.Context, in *pb.GetTradingLimitsRequest, opts ...grpc.CallOption) (*pb.TradingLimits, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTradingLimits", varargs...)
	ret0, _ := ret[0].(*pb.TradingLimits)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTradingLimits indicates an expected call of GetTradingLimits.
func (mr *MockShioajiClientMockRecorder) GetTradingLimits(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTradingLimits", reflect.TypeOf((*MockShioajiClient)(nil).GetTradingLimits), varargs...)
}

// GetUsage mocks base method.
func (m *MockShioajiClient) GetUsage(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.UsageStatus, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUsage", varargs...)
	ret0, _ := ret[0].(*pb.UsageStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsage indicates an expected call of GetUsage.
func (mr *MockShioajiClientMockRecorder) GetUsage(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsage", reflect.TypeOf((*MockShioajiClient)(nil).GetUsage), varargs...)
}

// ListAccounts mocks base method.
func (m *MockShioajiClient) ListAccounts(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.ListAccountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAccounts", varargs...)
	ret0, _ := ret[0].(*pb.ListAccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockShioajiClientMockRecorder) ListAccounts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockShioajiClient)(nil).ListAccounts), varargs...)
}

// ListComboTrades mocks base method.
func (m *MockShioajiClient) ListComboTrades(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.ListComboTradesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListComboTrades", varargs...)
	ret0, _ := ret[0].(*pb.ListComboTradesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComboTrades indicates an expected call of ListComboTrades.
func (mr *MockShioajiClientMockRecorder) ListComboTrades(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComboTrades", reflect.TypeOf((*MockShioajiClient)(nil).ListComboTrades), varargs...)
}

// ListPositionDetail mocks base method.
func (m *MockShioajiClient) ListPositionDetail(ctx context.Context, in *pb.ListPositionDetailRequest, opts ...grpc.CallOption) (*pb.ListPositionDetailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPositionDetail", varargs...)
	ret0, _ := ret[0].(*pb.ListPositionDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPositionDetail indicates an expected call of ListPositionDetail.
func (mr *MockShioajiClientMockRecorder) ListPositionDetail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPositionDetail", reflect.TypeOf((*MockShioajiClient)(nil).ListPositionDetail), varargs...)
}

// ListPositions mocks base method.
func (m *MockShioajiClient) ListPositions(ctx context.Context, in *pb.ListPositionsRequest, opts ...grpc.CallOption) (*pb.ListPositionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPositions", varargs...)
	ret0, _ := ret[0].(*pb.ListPositionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPositions indicates an expected call of ListPositions.
func (mr *MockShioajiClientMockRecorder) ListPositions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPositions", reflect.TypeOf((*MockShioajiClient)(nil).ListPositions), varargs...)
}

// ListProfitLoss mocks base method.
func (m *MockShioajiClient) ListProfitLoss(ctx context.Context, in *pb.ListProfitLossRequest, opts ...grpc.CallOption) (*pb.ListProfitLossResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProfitLoss", varargs...)
	ret0, _ := ret[0].(*pb.ListProfitLossResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProfitLoss indicates an expected call of ListProfitLoss.
func (mr *MockShioajiClientMockRecorder) ListProfitLoss(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfitLoss", reflect.TypeOf((*MockShioajiClient)(nil).ListProfitLoss), varargs...)
}

// ListProfitLossDetail mocks base method.
func (m *MockShioajiClient) ListProfitLossDetail(ctx context.Context, in *pb.ListProfitLossDetailRequest, opts ...grpc.CallOption) (*pb.ListProfitLossDetailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProfitLossDetail", varargs...)
	ret0, _ := ret[0].(*pb.ListProfitLossDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProfitLossDetail indicates an expected call of ListProfitLossDetail.
func (mr *MockShioajiClientMockRecorder) ListProfitLossDetail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfitLossDetail", reflect.TypeOf((*MockShioajiClient)(nil).ListProfitLossDetail), varargs...)
}

// ListProfitLossSummary mocks base method.
func (m *MockShioajiClient) ListProfitLossSummary(ctx context.Context, in *pb.ListProfitLossSummaryRequest, opts ...grpc.CallOption) (*pb.ListProfitLossSummaryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProfitLossSummary", varargs...)
	ret0, _ := ret[0].(*pb.ListProfitLossSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProfitLossSummary indicates an expected call of ListProfitLossSummary.
func (mr *MockShioajiClientMockRecorder) ListProfitLossSummary(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfitLossSummary", reflect.TypeOf((*MockShioajiClient)(nil).ListProfitLossSummary), varargs...)
}

// ListSettlements mocks base method.
func (m *MockShioajiClient) ListSettlements(ctx context.Context, in *pb.GetSettlementsRequest, opts ...grpc.CallOption) (*pb.GetSettlementsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSettlements", varargs...)
	ret0, _ := ret[0].(*pb.GetSettlementsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSettlements indicates an expected call of ListSettlements.
func (mr *MockShioajiClientMockRecorder) ListSettlements(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSettlements", reflect.TypeOf((*MockShioajiClient)(nil).ListSettlements), varargs...)
}

// ListTrades mocks base method.
func (m *MockShioajiClient) ListTrades(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.ListTradesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTrades", varargs...)
	ret0, _ := ret[0].(*pb.ListTradesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrades indicates an expected call of ListTrades.
func (mr *MockShioajiClientMockRecorder) ListTrades(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrades", reflect.TypeOf((*MockShioajiClient)(nil).ListTrades), varargs...)
}

// Login mocks base method.
func (m *MockShioajiClient) Login(ctx context.Context, in *pb.LoginRequest, opts ...grpc.CallOption) (*pb.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Login", varargs...)
	ret0, _ := ret[0].(*pb.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockShioajiClientMockRecorder) Login(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockShioajiClient)(nil).Login), varargs...)
}

// Logout mocks base method.
func (m *MockShioajiClient) Logout(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.LogoutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Logout", varargs...)
	ret0, _ := ret[0].(*pb.LogoutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockShioajiClientMockRecorder) Logout(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockShioajiClient)(nil).Logout), varargs...)
}

// PlaceComboOrder mocks base method.
func (m *MockShioajiClient) PlaceComboOrder(ctx context.Context, in *pb.PlaceComboOrderRequest, opts ...grpc.CallOption) (*pb.ComboTrade, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PlaceComboOrder", varargs...)
	ret0, _ := ret[0].(*pb.ComboTrade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceComboOrder indicates an expected call of PlaceComboOrder.
func (mr *MockShioajiClientMockRecorder) PlaceComboOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceComboOrder", reflect.TypeOf((*MockShioajiClient)(nil).PlaceComboOrder), varargs...)
}

// PlaceOrder mocks base method.
func (m *MockShioajiClient) PlaceOrder(ctx context.Context, in *pb.PlaceOrderRequest, opts ...grpc.CallOption) (*pb.Trade, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PlaceOrder", varargs...)
	ret0, _ := ret[0].(*pb.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceOrder indicates an expected call of PlaceOrder.
func (mr *MockShioajiClientMockRecorder) PlaceOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceOrder", reflect.TypeOf((*MockShioajiClient)(nil).PlaceOrder), varargs...)
}

// ReserveEarmarking mocks base method.
func (m *MockShioajiClient) ReserveEarmarking(ctx context.Context, in *pb.ReserveEarmarkingRequest, opts ...grpc.CallOption) (*pb.ReserveEarmarkingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReserveEarmarking", varargs...)
	ret0, _ := ret[0].(*pb.ReserveEarmarkingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveEarmarking indicates an expected call of ReserveEarmarking.
func (mr *MockShioajiClientMockRecorder) ReserveEarmarking(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveEarmarking", reflect.TypeOf((*MockShioajiClient)(nil).ReserveEarmarking), varargs...)
}

// ReserveStock mocks base method.
func (m *MockShioajiClient) ReserveStock(ctx context.Context, in *pb.ReserveStockRequest, opts ...grpc.CallOption) (*pb.ReserveStockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReserveStock", varargs...)
	ret0, _ := ret[0].(*pb.ReserveStockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveStock indicates an expected call of ReserveStock.
func (mr *MockShioajiClientMockRecorder) ReserveStock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveStock", reflect.TypeOf((*MockShioajiClient)(nil).ReserveStock), varargs...)
}

// SubscribeTrade mocks base method.
func (m *MockShioajiClient) SubscribeTrade(ctx context.Context, in *pb.SubscribeTradeRequest, opts ...grpc.CallOption) (*pb.SubscribeTradeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeTrade", varargs...)
	ret0, _ := ret[0].(*pb.SubscribeTradeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeTrade indicates an expected call of SubscribeTrade.
func (mr *MockShioajiClientMockRecorder) SubscribeTrade(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeTrade", reflect.TypeOf((*MockShioajiClient)(nil).SubscribeTrade), varargs...)
}

// UnsubscribeTrade mocks base method.
func (m *MockShioajiClient) UnsubscribeTrade(ctx context.Context, in *pb.UnsubscribeTradeRequest, opts ...grpc.CallOption) (*pb.UnsubscribeTradeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnsubscribeTrade", varargs...)
	ret0, _ := ret[0].(*pb.UnsubscribeTradeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsubscribeTrade indicates an expected call of UnsubscribeTrade.
func (mr *MockShioajiClientMockRecorder) UnsubscribeTrade(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeTrade", reflect.TypeOf((*MockShioajiClient)(nil).UnsubscribeTrade), varargs...)
}

// UpdateComboStatus mocks base method.
func (m *MockShioajiClient) UpdateComboStatus(ctx context.Context, in *pb.UpdateStatusRequest, opts ...grpc.CallOption) (*pb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateComboStatus", varargs...)
	ret0, _ := ret[0].(*pb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComboStatus indicates an expected call of UpdateComboStatus.
func (mr *MockShioajiClientMockRecorder) UpdateComboStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComboStatus", reflect.TypeOf((*MockShioajiClient)(nil).UpdateComboStatus), varargs...)
}

// UpdateOrder mocks base method.
func (m *MockShioajiClient) UpdateOrder(ctx context.Context, in *pb.UpdateOrderRequest, opts ...grpc.CallOption) (*pb.Trade, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrder", varargs...)
	ret0, _ := ret[0].(*pb.Trade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockShioajiClientMockRecorder) UpdateOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockShioajiClient)(nil).UpdateOrder), varargs...)
}

// UpdateStatus mocks base method.
func (m *MockShioajiClient) UpdateStatus(ctx context.Context, in *pb.UpdateStatusRequest, opts ...grpc.CallOption) (*pb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStatus", varargs...)
	ret0, _ := ret[0].(*pb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockShioajiClientMockRecorder) UpdateStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockShioajiClient)(nil).UpdateStatus), varargs...)
}
